### ISSUE TITLE
Form_plugin & List_plugin: Article 3.1rc1 bugs

### ISSUE THREAD

**Issue by superdeluxxx** [Fabrik/fabrik#1074]
## FORM PLUGIN ##
- [x] The Intro and Main images are set in right place in the Joomla article but the url isn't right. Missing a / in the http:// and nothing behind main url

- [x] The title set in the plugin isn't filling the joomla article

- [x] In the plugin settings we state published = on. This isn't set in the J article

- [x] joomla ref id. not stored. keeps saving same articles

- [x] image in { }  in template isn't showing anything

- [x] Read more in the article used as template isn't copied to the article

## LIST PLUGIN ##
- [ ]  Not working as it should. Adds new items each time and shows white screen after update

**Comment by pollen8** [comment]
as of today they should be.
