### ISSUE TITLE
Displaying issues with content plugin

### ISSUE THREAD

**Issue by jaanusnurmoja** [Fabrik/fabrik#1192]
In form intro/outro: displaying details view with content plugin prevents element javascripts working. I.e. when I have some group hidden with an element js and there is some other record details displayed with content plugin then this group is shown. 

In group intro/outro: when displaying either list or details there, the query is correct but data not shown.

Placeholder [rowid] seems not to be parsed - i.e {fabrik view=list id=1 table___element=[rowid]}, query is generated without where clause

**Comment by pollen8** [comment]
row id is fixed - I didnt see any js errors.
Group intro / outro in details view worked. They dont seem to be parsed in the form view.
