### ISSUE TITLE
Filters not quoting values of IN() under certain circumstances

### ISSUE THREAD

**Issue by cheesegrits** [Fabrik/fabrik#1210]
As per this thread:

http://fabrikar.com/forums/index.php?threads/bug-missing-quotes-if-pre-filter-with-in-condition-and-additional-user-filter.37648/#post-190762

I've been working my way through trying to make sure we always quote values, even if we think they are PK's, but I've obviously missed a few.

**Comment by pollen8** [comment]
seems to be fixed in the thread
