### ISSUE TITLE
Loading spinner off screen

### ISSUE THREAD

**Issue by cheesegrits** [Fabrik/fabrik#1229]
With the "show loader on submit" for forms option, the loader only covers the form itself, so if you are scrolled down on a form longer than a screenful, the spinner itself is often not visible.

@pollen8  Can we modify the loader so it covers the viewport, rather than the form?

http://fabrikar.com/forums/index.php?threads/show-loader-on-submit-not-showing-spinner.38226/#post-192237

**Comment by pollen8** [comment]
@cheesegrits - what/where is the 'show loader on submit" for form options? I can't see it now, might it have been removed, and if so can we close this ticket?

**Comment by jaanusnurmoja** [comment]
Some spinner or even rather a status bar (with some text) would be welcome alse when we are loading list/details and in whatever reason it's slow

**Comment by cheesegrits** [comment]
http://screencast.com/t/EG11ZX5JZcu

   -- hugh

**Comment by pollen8** [comment]
closing - seems to be a none issue for me
