### ISSUE TITLE
CSV list data export failure

### ISSUE THREAD

**Issue by dahagag** [Fabrik/fabrik#1232]
While trying to export data the export dialog freezes at 0 record:
"Loading
0 / records.
saving to"

This is the console log:

[object Object] list-min.js:1
[object Object] list-min.js:1
POST http://localhost/fablab/administrator/index.php [HTTP/1.1 303 See other 525ms]
GET http://localhost/httplocalhostfablabadministratorindex.phpoptioncom_fabriktasklist.viewlistid15 [HTTP/1.1 404 Not Found 10ms]
TypeError: g is undefined

**Comment by vincenzo-86** [comment]
> While trying to export data the export dialog freezes at 0 record: "Loading 0 / records. saving to"
> 
> This is the console log:
> 
> [object Object] list-min.js:1 [object Object] list-min.js:1 POST http://localhost/fablab/administrator/index.php [HTTP/1.1 303 See other 525ms] GET http://localhost/httplocalhostfablabadministratorindex.phpoptioncom_fabriktasklist.viewlistid15 [HTTP/1.1 404 Not Found 10ms] TypeError: g is undefined

Good evening
I have the same problem, you find a solution?

**Comment by trob** [comment]
Please use Fabrik forums. This is a 10 years old, closed issue related to Fabrik3 (or even lower).
