### ISSUE TITLE
email option in update_col plugin

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1233]
I've added a fix so it's working now if a field element is selected as email address.
But it is still not working if selecting a user element (and I don't know what the code is supposed to do with multiple row ids).

Notice: Undefined variable: item in ...\plugins\fabrik_list\update_col\update_col.php on line 352
Notice: Trying to get property of non-object in ...\plugins\fabrik_list\update_col\update_col.php on line 352
Warning: Invalid argument supplied for foreach() in ...\plugins\fabrik_list\update_col\update_col.php on line 356

**Comment by pollen8** [comment]
at a guess I would say this one is fixed - I can see that $item is now defined on line 361
