### ISSUE TITLE
order_by, order_dir in query string

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1247]
see http://www.fabrikar.com/forums/index.php?threads/querystring-order-by-not-working-with-multiple-elements.38440/

in  \components\com_fabrik\models\list.php
$input->get('order_by', '') (e.g. line 2753) is returning the string without ","
$input->getString('order_by', '') is working but I don't know if this has side effects

Same in Fabrik3.0

**Comment by pollen8** [comment]
seems its been resolved in the thread
