### ISSUE TITLE
Strict Standards: Declaration of PlgFabrik_ElementUser::_getSelectLabel() should be compatible with PlgFabrik_ElementDatabasejoin::_getSelectLabel($filter = false) in htdocs\fabrik\plugins\fabrik_element\user\user.php on line 25

### ISSUE THREAD

**Issue by navjinder** [Fabrik/fabrik#1253]
Change protected function _getSelectLabel()  to protected function _getSelectLabel($filter = false) in \fabrik_element\user\user.php 

( Fabrik joomla3 branch )

![fabrikissue1](https://cloud.githubusercontent.com/assets/3472650/3107945/00aa2dd0-e68b-11e3-9764-ef81923d6a25.PNG)

**Comment by pollen8** [comment]
I think these are all ok now - closing
