### ISSUE TITLE
F3.1 plugins missing from fabrikar.com download list

### ISSUE THREAD

**Issue by Sophist-UK** [Fabrik/fabrik#1259]
The following plugins are in the GitHub Joomla3 branch but are not in the F3.1 base distribution and are missing from the download list on fabrikar.com:

Fabrik Module - Tag Cloud
Fabrik Visualization
Fabrik Cron - Gmail
Fabrik Cron - REST
Fabrik Element - Access
Fabrik Element - Count
Fabrik Element - Thumbs
Fabrik Form - FTP
Fabrik Form - Logs
Fabrik Form - REST
Fabrik Form - Paypal Subscriptions
Fabrik List - Filter View
Fabrik List - Pivot table
Fabrik Validation - is numeric
Fabrik Validation - is unique
Fabrik Validation - Open provider
Fabrik Visualization - Approvals
Fabrik Visualization - nvd3 Chart
Search - Fabrik
System - Fabrik Scheduled Tasks

**Comment by pollen8** [comment]
ive added the flollowing 

Fabrik Element - Access
Fabrik Element - Thumbs
Fabrik Form - FTP
Fabrik Form - Logs
Fabrik Form - REST
Fabrik Form - Paypal Subscriptions
Fabrik List - Pivot table
Fabrik Validation - is numeric
Fabrik Validation - is unique
Fabrik Validation - Open provider
Search - Fabrik

some of the others are not working, dont have download zips built, etc

**Comment by HeartPraise** [comment]
fabrik package is missing the Fabrik cron system plugin for schedule
