### ISSUE TITLE
'Order by' broken when using concat label with databasejoin field

### ISSUE THREAD

**Issue by batonac** [Fabrik/fabrik#1261]
When using a concat label with a databasejoin field in Fabrik 3.1 (latest from Github), enabling 'order by' in the list view settings, and attempting to order the list by that column from the list view, the resultant query uses the entire concat string in the 'ORDER BY' clause, instead of using calling the column alias.

For example, when I enter, `{thistable}.number,' ',{thistable}.name` into the concat label field, and then try to sort by that databasejoin element column, the resultant query contains both `CONCAT_WS('', threecore_category.number,' ',threecore_category.name) AS threecore___category_id` in the SELECT clause, and `ORDER BY CONCAT_WS('',threecore_category.number,' ',threecore_category.name) asc'` at the end.  It should say `ORDER BY threecore___category_id asc` instead...

**Comment by pollen8** [comment]
this seems to be fixed. Closing the ticket. If its still an issue please feel free to reopen it
