### ISSUE TITLE
Pop ups on the event calendar visualization are not closing in Chrome browser.

### ISSUE THREAD

**Issue by TurtleWolf** [Fabrik/fabrik#1326]
I love Fabrik... I just discovered it 2 weeks ago. If I hadn't found a good solution for C.R.U.D. in Joomla I was going to have to continue shopping for the right framework. But you've nailed it. anyways, to the bug. I've just completed your vimeo on an app in 30 minutes and I've noticed the pop ups over the calendar visualization will not respond to clicking on the closing "x" in the upper right corner. //button class="close" data-popover="fabrikEvent_4_4"//×///button//

**Comment by pollen8** [comment]
seems to be working for me, closing this ticket.
