### ISSUE TITLE
list ajax update, layout issue with element calculations

### ISSUE THREAD

**Issue by pollen8** [Fabrik/fabrik#133]
if you have a field with sum/avg/etc calculations turned on, and update the list via js (e.g. you can do 
Fabrik.blocks['list_1_com_fabrik_1'].updateRows();
)
then the calculation is moved from the bottom to the top of the list

**Comment by trob** [comment]
This was fixed here
Moved calculations into a tfoot in main bootstrap tmpl for lists (2015-01-13 16:53:22)

I don't know how to get the commit with the SHA1ID shown in my Git GUI (or to search the text) :-(
