### ISSUE TITLE
yes/no element with "Single Yes" = yes

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1338]
issue1:
it doesn't check if the yesno element is YES at all. Even if it's NO it's setting all other rows to NO.

issue2:
if adding a row the rowid is not known, so it's throwing 
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 3 SQL=UPDATE liste_einfach SET yn2 = 0 WHERE `liste_einfach`.`id` <>
Fix: add around line 457
	$rowid = $rowid == ""? 0 : $rowid;
	$query->update($this->actualTableName())->set($name . ' = 0')->where($pk . ' <> ' . $rowid);

**Comment by cheesegrits** [comment]
Jaanus - the comitt closed this issue, as it resolves the bug(s).  Can't keep an issue open pending impementing feature requests unrelated to the actual bug.
