### ISSUE TITLE
jUser plugin is clearing form data; delete user not working

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1342]
1. 
After creating a new user via jUser plugin you can't use {table___element} placeholders in an email plugin, they are empty (tested with the elements linked to name and email).
(jUser is doing some session stuff, maybe clearing these elements?)

At least the _raw placeholders are working.

2.
After deleting a record in the Fabrik list the Joomla user is still existing (Delete users =YES).

**Comment by pollen8** [comment]
1 - I am not able to replicate this one. I tested with the element linked to the name. I tested on creating a new user and editing an existing user. I was adding the placeholders in the email plugin's 'Element text' textarea

**Comment by pollen8** [comment]
2 - user delete also seems to work. Closing this ticket, Feel free to re-open if there's something still not right
