### ISSUE TITLE
nvd3_chart default tmpl minor typo and fix

### ISSUE THREAD

**Issue by navjinder** [Fabrik/fabrik#1347]
On the default template [file](https://github.com/Fabrik/fabrik/blob/joomla3/plugins/fabrik_visualization/nvd3_chart/views/nvd3_chart/tmpl/default/default.php#L27)

The typo is on line 27

the typo:
```html
<svg style="height:<?php echo $this->params->get('height', 350); ?>px;width="<?php $this->params->get('width', 350)?>px"></svg>
````
the fixed version: 

```html
<svg style="height:<?php echo $this->params->get('height', 350); ?>px;width=<?php echo $this->params->get('width', 350); ?>px"></svg>
```

**Comment by pollen8** [comment]
thanks I've now commit that
