### ISSUE TITLE
"append jump url with data" and array elements

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1350]
See
http://www.fabrikar.com/forums/index.php?threads/ajex-file-upload-post-array-incorrect.40206/

I assume
line 312 in plugins\fabrik_form\redirect\redirect.php should be ...[value][]
				foreach ($val as $v)
				{
					$this->_appendQS($queryvars, "{$key}[value][]", $v, $appendEmpty);
				}

**Comment by timomer** [comment]
fyi - the fix above creates an array inside an array called "value", what's not ideal. The following creates the expected array:
$this->_appendQS($queryvars, "{$key}[]", $v, $appendEmpty);

**Comment by trob** [comment]
element[value][] is used in Fabrik list filtering (together with [condition])
