### ISSUE TITLE
creating a filter form like JED??

### ISSUE THREAD

**Issue by msseemorgh** [Fabrik/fabrik#1371]
Hello there
Does any one know how to use tag plug-in to filter joomla articles by multiple tags?
I mean I made a group of elements which is made from joomla core content table with two joins on it.... let me say it more clear ...:
           first I made a list from
                     joomla-core-data base -----> _content 
           then I put two joins on it
                     first join is ---->_content   with   _contentitem_tag_map
                       second join is a join with the result of above and ----> _tags
          now I have a list which show content and their tags together
                    then I made a new form which is not connected to a db table and is not recording  data...
                    now I create a new element whit the same name as tag_id and the plugin of this new
                    element is tag.....
          then I put a redirect plugin in the search form and I set the jump page to
                     http://localhost/draft/test-thing?option=com_fabrik&view=list&listid=1
                      test-thing is my list menu item and it's fabrik ID is 1
     now when I select some tags and submit the form I get this in the url
              http://localhost/draft/test-thing?option=com_fabrik&view=list&listid=1&___tag_id[value]=4&___tag_id[value]=6&___tag_id[value]=8&___title=

which does work but with one small flaw.......

what I need is to filter article by multiple tags like if I select 3 different tags result must be all the article that have all those three.... but... what it shows now is any article with any of those tags....... I mean it show an article which has only one of the tags too.....

what I'm trying to say is where can we define our filter to use AND instead of OR in their query.....

well sorry if I can't say it clearly but what I want is something exactly like the new JED....

An advance search form with tag filter, that's what I want and I can't find any straight tutorial or document or anything about that anywhere.

it seems I don't know anything about anything!! 
is there the right place to ask such things?
sorry if it's not, please help me about that too, because I couldn't signup for fabrik forum :(

**Comment by trob** [comment]
"because I couldn't signup for fabrik forum"
Did you register on fabrikar.com?
Try to log out, clear browser cache.
