### ISSUE TITLE
webservice list plugin: no button

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1372]
webservice list plugin doesn't show a button in Fabrik3.2
http://www.fabrikar.com/forums/index.php?threads/web-service-configuration-problem.40469/

It's working (in terms of showing the top button, I didn't test anything else) in Fabrik3.0

**Comment by jaanusnurmoja** [comment]
Now it shows the button (unfortunately not near the pdf, csv etc buttons, but in the edit/view/delete heading). 
The plugin itself only imports new content when nothing was imported earlier but any update fails
