### ISSUE TITLE
TypeError: window[h[0]] is not a constructor 

### ISSUE THREAD

**Issue by gadeynebram** [Fabrik/fabrik#1374]
Hi,

I'm getting an error in fabric 3.2 when using the following content reference in an article.

{fabrik view=form id=2 ticketing_comments___issue_raw=[meldingid]}

TypeError: window[h[0]] is not a constructor  in form-min.js on row 1, column 11215.

It seems to be related to an upload file field that I'm using (with or without ajax upload).

Does anyone have any idea how to solve this?

**Comment by cheesegrits** [comment]
Can you enable Fabrik debugging in the global options, set it to "Debug JS" and reload the page.  That should load the uncompressed JS.  Let us know the line number of the error.

**Comment by pollen8** [comment]
no reply from OP - closing
