### ISSUE TITLE
extend search all is doing ...AGAINST ('mr*' IN BOOLEAN MODE) )

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1377]
Shouldn't it be
AGAINST ('%mr%' IN BOOLEAN MODE) )
i.e. wildcard also at the beginning (had to substitute * with % because of markdown)?

So something like
			case 'any':
				$operator = '*';
				break;
			default:
			case 'exact':
				$operator = '';
				break;
\components\com_fabrik\models\listfilter.php line 450

Why is * added in any case (i.e. also if searching for "exact")?

**Comment by cheesegrits** [comment]
Nope.  As per our Skype conversation, IN BOOLEAN MODE only matches full words, or words starting with the pattern.
