### ISSUE TITLE
AJAX loaded content loading encoded HTML

### ISSUE THREAD

**Issue by MoleInc** [Fabrik/fabrik#1391]
I have a Cascading Drop Down element loading content based off another dropdown, the cascading element is actually a list of radio buttons with HTML in their CONCAT label. When the dropdown changes and triggers a AJAX reload, the content that is inserted is inserted as 'text' instead of 'html' so the HTML based label I have when reloaded loads as plain text and prints the html tags out, sample below:

From:
![Before AJAX update](http://www.aaronfrancis.com.au/github/fabrik/20150224_fabrikbug1.png)

To:
![After AJAX update](http://www.aaronfrancis.com.au/github/fabrik/20150224_fabrikbug2.png)

I managed to fix this for myself by editing the databasejoin.js (which its using the addOption function from) on line 200 from this:

`}), new Element('span').set('text', l)]));`

to this:

`}), new Element('span').set('html', l)])); // 2015-02-24 12:21pm Was 'text', changed to 'html' to allow for AJAX loaded labels containing HTML`

Look at the checkbox code above this I also changed line 171 in the same way.

**Comment by cheesegrits** [comment]
I'm looking at this.  I seem to recall some reason we used text rather than html, I'm just trying to remember what it was.

**Comment by pollen8** [comment]
Closing this as the changes are in the codebase.

**Comment by cheesegrits** [comment]
::hangs head in shame::

I keep forgetting to close issues after they get fixed.
