### ISSUE TITLE
Cascading Drop Down Auto Complete

### ISSUE THREAD

**Issue by keith4061** [Fabrik/fabrik#1416]
Does Auto Complete work on Cascading Drop Down? I have a db join and then a CDD which is set to auto complete for name, although this does not work. 
It does work when render is set to dropdown, although I have to select it. Please can someone help as I have been looking for a solution for this. I have also been on the Fabrik forums and no response.

**Comment by trob** [comment]
I can't see a keith4061 post in the forums.
Can you please post there mentioning your Joomla and Fabrik version?
Maybe including links to other posts you are referring to.

**Comment by pollen8** [comment]
working for me - closing this thread
