### ISSUE TITLE
custom link in DETAILS view using an element from repeat group

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1431]
http://www.fabrikar.com/forums/index.php?threads/custom-links-in-repeatable-joined-group.40927/

I can see what is going on but not how to fix it:
In details view  \components\com_fabrik\models\element.php in function addCustomLink (line 2402 ..)

 two remarks  (nothing to do with the issue)
1. it must be $customLink = $params->get('custom_link',''); 
otherwise it's trying to add a custom link to every element becaus $customLink is NULL
2. addCustomLink is called twice for every element, why? (checked with var_dump($this->element->id) )

issue:
$data[element-in-repeat-group] is an array and parseMessageForPlaceHolder is returning the imploded values.
If I do 
```
$w = new FabrikWorker;
			$repData = array();
			foreach ($data as $k => $val)
			{
				$repData[$k] = $val;
				if (is_array($val)) {
					$repData[$k] = $val[$repeatCounter];
				}
			}

			$customLink = $w->parseMessageForPlaceHolder($customLink, $repData);
```
it's working like in list view:
If a main-list element is using the repeat-element-placeholder it's always replaced with the first value of the array (repeatcounter=0)
If a repeat-group-element is using this placeholder it's replaced with the correct (expected) value of this element's repeatcounter.

But:
In case of repeat-group-elements $data has some more strange entries if the form contains dbjoin elements (test is the parent table, test3 the joined table)
...expected $data array until "html"
string(5) "rowid" string(2) "11"
string(6) "format" string(4) "html"
string(25) "test___j_fbuserreg_ro_raw" array(1) { [0]=> string(1) "4" }
string(25) "test3___dbjoint3_ro_0_raw" array(1) { [0]=> string(2) "11" }
string(23) "test3___userid_ro_0_raw" array(1) { [0]=> string(3) "426" }

adding some more for the next repeat-group-element 
...
string(6) "format" string(4) "html"
string(25) "test___j_fbuserreg_ro_raw" array(1) { [0]=> string(1) "4" }
string(25) "test3___dbjoint3_ro_0_raw" array(1) { [0]=> string(2) "11" }
string(23) "test3___userid_ro_0_raw" array(1) { [0]=> string(3) "426" }
string(25) "test3___dbjoint3_ro_1_raw" array(1) { [0]=> string(2) "11" }
string(23) "test3___userid_ro_1_raw" array(1) { [0]=> string(3) "426" }

and so throwing errors if repeatcounter is >0 because of $val[$repeatCounter]
Notice: Undefined offset: 1 in C:\xampp54\htdocs\j33\components\com_fabrik\models\element.php on line 2423

**Comment by cheesegrits** [comment]
Fixed as of this commit:

https://github.com/Fabrik/fabrik/commit/b22878dbd04938433506d1dbda3aa12defcb8495
