### ISSUE TITLE
Birthday: no data in edit mode, validationrule and chzn not working

### ISSUE THREAD

**Issue by jaanusnurmoja** [Fabrik/fabrik#1457]
Something went wrong with implemention of JLayouts for birthday element:
* when editing existing data, the element returns no data
* validationrule doesn't work 

See http://fabrikar.com/forums/index.php?threads/birthday-plugin-validation-rule-and-edit-issues.41143
* in chosen mode the search field that appears on the top is not able to find data from dropdown

All these issues occurred after commit https://github.com/Fabrik/fabrik/commit/b0d1478b22e0fdbc42cdc9f1a0b648c37356fa92

So birthday element seems to be working normally when reverted to the following state (before the commit mentioned above):
https://github.com/Fabrik/fabrik/tree/f72d1a987bd9867b454d992eee7bef61690b9c55/plugins/fabrik_element/birthday

**Comment by trob** [comment]
Edit and add are working if in \plugins\fabrik_element\birthday\layouts\fabrik-element-birthday-form.php  === is changed to == in
$selected = $opt->value == $d->day_value ? ' selected="selected" ' : ''?> etc.
(opt->value =1, opt->day_value = 01)

**Comment by trob** [comment]
dataConsideredEmpty is checking/exploding
if (strstr($data, ','))
but the empty data is '--'

As far as I can see in the code birthday is mostly using '-' as connector and in explode
but it's doing
list($year, $month, $day) = strstr($value, '-') ? explode('-', $value) : explode(',', $value);
in line 114?
