### ISSUE TITLE
Captcha dont work

### ISSUE THREAD

**Issue by mlacunza** [Fabrik/fabrik#1464]
Captcha is only showed when I put Debug System = Yes

Joomla 3.4.1, Fabrik 3.3.2 and element - captcha plug-in 3.3.2 

Thats for all captcha options.

**Comment by trob** [comment]
Can you please post in the forums?
GitHub issue is for confirmed issues only.
Update from GitHub to get the latest code.

**Comment by mlacunza** [comment]
Thats the problem, I cant login into the forum, each time I try I got this error message in forum:

Error
        Master User Authentication Failed

I try with 2 differents accounts: 
mlacunza[at]gmail[dot]com
mario[at]lacunza[dot]biz

can you check what happen? thanks!

**Comment by mlacunza** [comment]
and I use the latest version downloaded from the Fabrik website, need to test with git version?I think its the same

**Comment by pollen8** [comment]
please contact us via email to get your password reset
The git version is not the same as the download, its a working progress towards the next release

**Comment by mlacunza** [comment]
Done!
But its a stable version and I see some people working with my same config with no issues :( 
Thanks for your help!

**Comment by cheesegrits** [comment]
"Stable" is a relative term.  :)
