### ISSUE TITLE
Map crash with no data

### ISSUE THREAD

**Issue by mlacunza** [Fabrik/fabrik#1465]
I add in a visualization map some lists, an error is showed when some of the tables linked dont have any record yet. The page is not showed and crash.

Joomla 3.4.1, Fabrik 3.3.2

**Comment by trob** [comment]
I can't replicate.
Can you please post in the forums?
GitHub issue is for confirmed issues only.

**Comment by mlacunza** [comment]
if you want replicate it:
1. Create a list with empty data and add some fields.
2. Create Map Visualization
3. in my case I add it using the plugin inside of article
4. Load front end page and I got error message.

If I add one record to the list the map is loaded with no issues.

I cant login into the forum, each time I try I got this error message in forum:

Error
Master User Authentication Failed

I try with 2 differents accounts:
mlacunza[at]gmail[dot]com
mario[at]lacunza[dot]biz

can you check what happen? thanks!

**Comment by cheesegrits** [comment]
What is your forum name?

**Comment by cheesegrits** [comment]
Oops, n/m, just saw the emails you specified.

**Comment by felixkat** [comment]
Cannot find forum post about this issue so it cannot be confirmed.  Therefore closing.  Please post issue on forum if this issue still exists.
