### ISSUE TITLE
content plugin "view=element""

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1475]
element is displayed (raw value) even if unpublished
but throwing notices/warnings
in case of a dbjoin e.g.
Notice: Trying to get property of non-object in C:\xampp54\htdocs\j33\plugins\fabrik_element\databasejoin\databasejoin.php on line 2371

Notice: Trying to get property of non-object in C:\xampp54\htdocs\j33\plugins\fabrik_element\databasejoin\databasejoin.php on line 1030

Notice: Trying to get property of non-object in C:\xampp54\htdocs\j33\plugins\fabrik_element\databasejoin\databasejoin.php on line 2371

Notice: Trying to get property of non-object in C:\xampp54\htdocs\j33\plugins\fabrik_element\databasejoin\databasejoin.php on line 859

Warning: Invalid argument supplied for foreach() in C:\xampp54\htdocs\j33\libraries\joomla\database\driver.php on line 1487

Notice: Array to string conversion in C:\xampp54\htdocs\j33\plugins\fabrik_element\databasejoin\databasejoin.php on line 859

I assume this is also the reason here
http://www.fabrikar.com/forums/index.php?threads/error-messages-above-article-with-fabrik-content.40576/page-2

**Comment by cheesegrits** [comment]
Ah HAH!  Well spotted!  Working on that now.

**Comment by cheesegrits** [comment]
Should be fixed with:

https://github.com/Fabrik/fabrik/commit/afcced9aa157202bcfa078a9f3dc9dc6849c8928
