### ISSUE TITLE
decide if we keep parent/child elements

### ISSUE THREAD

**Issue by pollen8** [Fabrik/fabrik#1482]

**Comment by pollen8** [comment]
beate: But at least it should be possible to filter on full element names to get all elements "belonging" to one table column (is not possible at the moment)

beate: so I think unlinked elements are ok - as long as you can find out which ones "belong" together (and it would be very nice to have an icon "this is not the only one with this element name" in the element listing)

jaanus: I would prefer a feature "set the same params also for other elements with the same full name: 1) manually selected 2) for all using the same element plugin 3) for all

**Comment by cheesegrits** [comment]
Januus' suggestion sounds good.

**Comment by pollen8** [comment]
How do you see that one working? As a global option and then the settings are read in when say copying a list?

**Comment by pollen8** [comment]
My idea was to simply copy a matched elements settings on copy. I'm struggling to see where you would want to use the 'manually selected' and 'all using the same element plugin' options though.

**Comment by jaanusnurmoja** [comment]
In element admin form.
say element name is table___field and totally we have it 5. 
This one where we are is calc element.in List 1 - Form 1

We go to the tab "other similar elements" and we see:
Set the same params also for other table___field elements?
1) no (default)
2) when the element plugin is same (you are using calc)
3) for all (warning - all the elements will become calc elements)
4) select manually (selecting this option opens a list with other elements)

Other elements table___field 
List 2 - Form 2 (field)
List 3 - Form 3 (field)
List 4 - Form 4 (databasejoin)
List 5 - Form 5 (calc)

option 2 - we change current element and List 5 - Form 5 (calc)
With option 4 we can select needed elements manually. When we select List 4 - Form 4 (databasejoin) it will be calc instead.

So it's one possible alternative to the "child elements". 

Other - we could think about a possible "master" collection. So we could choose in element options "Use master... (and choose the needed one from the list of master elements). But it would be just for editing session, not "linking".
