### ISSUE TITLE
submit form without reload page

### ISSUE THREAD

**Issue by micker** [Fabrik/fabrik#1485]
hello
sorry for this issue but in can't register and login in fabrikar site (salt error) ...
i have a form with fabrik 3.0.6.3 i try to actived ajax validation but form is always reload ...
i realy need an validation in my field without this (i loadin some information in preview page...)
thanks for your help

**Comment by cheesegrits** [comment]
What is your username on the forums?

**Comment by micker** [comment]
yberges

**Comment by micker** [comment]
now i have this error
Master User Authentication Failed

**Comment by cheesegrits** [comment]
I just reset your password, am mailing it to the address you registered
with.

**Comment by felixkat** [comment]
The title and forum post suggest this possible issue was for a very old version of Joomla & Fabrik.

The forum post went stale......

http://fabrikar.com/forums/index.php?threads/submit-form-without-reload-page.41287/#post-208395

If this is still a problem with the latest code then please log a new issue.
