### ISSUE TITLE
non-existent files in pkg_fabrik_sink.xml

### ISSUE THREAD

**Issue by bauer-git** [Fabrik/fabrik#1490]
Looking at the pkg_fabrik_sink.xml file that is included from github - as well as the one included in the main fabrik download for version 3.3.2 at http://fabrikar.com/download - I see that, while the `<version>` tag is correct, all of the `<file>` tags reference non-existent zip files. 
![pkg_xml](https://cloud.githubusercontent.com/assets/2026714/7554629/73778ea6-f6fd-11e4-8655-f74bc62a1161.png)
Shouldn't those all have been changed to *_3.3.2.zip???

**Comment by pollen8** [comment]
the build is hopefully working correctly, please feel free to reopen if its still an issue
