### ISSUE TITLE
update_col plugin, multiple, with email

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1499]
line 292
				$row = $model->getRow($id, true);
is resetting the params to the ones of the last update_col_plugin (in line 268 $params is fetching the correct, plugin-related ones)

so
$params = $this->getParams();
in 
function emailTo()
and
function getEmailElement()
is fetching the wrong params.

not sure what is the best way to fix this how/where

**Comment by cheesegrits** [comment]
I'll hack this one for now by just doing ...

$this->params = $params;

... after the getRow() call, but we really need to work out a longer term solution  The problem being that getRow() resets the entire list model, including setting params back to null and reloading, which causes the plugin params to reload, as they are just part of the main list model.

**Comment by cheesegrits** [comment]
Should be "fixed" with this commit:

https://github.com/Fabrik/fabrik/commit/e64d26c52f843c39153592c19f0c7184d99c5fa9
