### ISSUE TITLE
Error Fileupload element: On deleting the file it empties the whole column

### ISSUE THREAD

**Issue by navjinder** [Fabrik/fabrik#1504]
Hi Fabrik Team

I am getting a peculiar error when I am using the file upload. Non-Ajax upload the files are loading perfectly and displaying the links too but when I delete the file to replace it then it deletes all the links in that column in mysql?

On Ajax it uploads the file to the server but when I save the form it do not save the file link it in the database.

```
Joomla version: 3.4.1
Fabrik version: latest github build (May 29, 2015)
```

**Comment by felixkat** [comment]
Is this still an issue?

**Comment by felixkat** [comment]
Cannot comfirm if this is stil an issue, so closing.
