### ISSUE TITLE
Typo in fileupload.php causes 'Drop box height' to be always 200px

### ISSUE THREAD

**Issue by ZoFx** [Fabrik/fabrik#1506]
Concerns version 3.3.2.

The fabrik element 'fileupload' offers settings (under 'Ajax uploads') to set the width and height of the AJAX dropbox. However, the file /plugins/fabrik_element/fileupload/fileupload.php contains a typo which prevents the height setting from ever being applied.

Line 2404 reads:
		$h = (int) $params->get('ajax_dropbox_hight', 200);

It should read:
		$h = (int) $params->get('ajax_dropbox_height', 200);

**Comment by trob** [comment]
Thanks, but this has already been fixed in GitHub (shortly after the 3.2.2 release).
You may update from GitHub to get the latest code (as always backup before).

**Comment by ZoFx** [comment]
Ok, great. Sorry for double posting then.
