### ISSUE TITLE
content plugin triggered by {fabrik_xxx___element} in Scheduled email message body

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1516]
and so throwing "500 Please specify a valid view type in your fabrik {} code:"

http://www.fabrikar.com/forums/index.php?threads/help-500-please-specify-a-valid-view-type-in-your-fabrik-code.41641/

Tested:
placeholder {fabrik_xxx___element} in "To" is ok, but in message body it's throwing the error.

**Comment by cheesegrits** [comment]
I think this is fixed in this commit:

https://github.com/Fabrik/fabrik/commit/bc6f9e037bec62e63cdf279da096a14f517c3f13
