### ISSUE TITLE
Fatal Error when field element Guess link type is switch ON

### ISSUE THREAD

**Issue by ariouche** [Fabrik/fabrik#1521]
Hello,

If a display a list where I've had switch ON Guess link type, that cause a 
Fatal error: Class 'PHPMailer' not found in /home/akconsul/www/components/com_fabrik/helpers/parent.php on line 1743

rgds

**Comment by trob** [comment]
I can't replicate.
Can you please post in the forums, mentioning your exact Joomla and Fabrik version, list settings, config settings etc.

**Comment by pollen8** [comment]
Pretty sure this one was fixed in a forum conversation - closing for now. Feel free to re-open if its still an issue
