### ISSUE TITLE
Article form plugin

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1529]
__Publish up date__ (I assume same with publish down, but not tested) is adding the TZ offset twice (or not converting to UTC for the article):
setup:
date element, UTC, my TZ is UTC+2
adding an article is showing e.g. 12:38 in Fabrik form/list (10:38 in DB) but 14:38 in Joomla article (12:38 in #_content)

__Author__: is setting "created by", not "author" which is at least a bit misleading

__Duplicate titels__:
on new:
Fabrik list/form is showing the duplicate title without increment (eg xxx)
the Joomla title is created as "xxx (2)", alias "xxx-2"
(creating a new article via Joomla will create the title as "xxx" while incrementing only the alias "xxx-3")

on edit:
changing the title to an existing one will change the Fabrik record but not the Joomla article; no error message ("record added/updated")

Question: alias must be unique per category?

**Comment by pollen8** [comment]
yes alias is unique per category
