### ISSUE TITLE
JS not triggering with radiobutton button group=yes 

### ISSUE THREAD

**Issue by kirancheema** [Fabrik/fabrik#1553]
Hi don't know if this is related to previous ticket or not #1224? 

using Joomla 3.4.3 Fabrik 3.3.3 

Created form with yes/no radio buttons 
Button Group = yes 

Javascript -> onclick if element = no then hide a textbox 

have tried using the predefined actions and attempted to use my own JS 

This work fine until you look at the page in Internet explorer 
in IE 8/9& 11 it doesn't work have tried the onClick/change and select events 

The only thing I can do is add something in the load event e.g. element.click(function(){})

If You switch button Group = OFF then that all works properly. 
all the events are triggered. 

is a real shame as I am forced to use the radio buttons to ensure compatibility... unless I'm doing something wrong?

**Comment by trob** [comment]
Can you please post in the forums?
Yes/no as button group with "onclick" hiding/showing an element is working fine (even in IE11).
I don't think any issues with IE8/9 are supported.

**Comment by kirancheema** [comment]
Thanks will post in forums as well.

The real issue was that everything works fine if button group = No but fails if button Group= Yes 
In IE 8

**Comment by Sophist-UK** [comment]
Also please check the JS console for errors.

**Comment by kirancheema** [comment]
thanks no errors showing on console (IE developer tools)

**Comment by pollen8** [comment]
I'm pretty sure you should use onchange on radio buttons, not on click which depending on the browser is fired before/after the value is actally changed.

**Comment by kirancheema** [comment]
Hi 
I did try the onchange event as well as and it didn't trigger. The only thing that I managed to get working was to create an event trigger Via onload.. I have posted more in the forum 

http://fabrikar.com/forums/index.php?threads/radio-buttons-and-ie8.42230/#post-213711
