### ISSUE TITLE
Off Topic: Bug in the JED com_jed extension

### ISSUE THREAD

**Issue by demis-palma** [Fabrik/fabrik#1556]
Hello,
I've found a bug in the JED, which causes that some reviews don't appear in the list.
I've reported this to the JED support with a ticket 15 days ago, but they don't even reply.
Can we get in touch to discuss about that?

**Comment by pollen8** [comment]
sorry this is a fabrik bug tracker - anything to do with the JED should, as you have done, be dealt with via their tracker
