### ISSUE TITLE
Weird "password" and "notes" in backend "Components" menu

### ISSUE THREAD

**Issue by UberGruber** [Fabrik/fabrik#1559]
Hey there, as per title, I've noticed 2 new *weird looking* voices in my Administration backend panel in the "Components" menu. This is in my local working machine, and I've installed like a week ago Fabrik with the Github updates. I'm using last Joomla 3.4.5 on a windows machine with XAMPP.

![menu components](https://cloud.githubusercontent.com/assets/1172428/10861341/d02024ea-7f7b-11e5-9750-f6cb610e041d.png)

Luckly enough with a quick search in the databse I found those voices are from 2 of your plugins "password" and "notes". (the red marked number are IDs)

Image from "menu" table
![menu id](https://cloud.githubusercontent.com/assets/1172428/10861346/ea3edc0e-7f7b-11e5-9207-3008bbc4f932.jpg)

Image from "extensions" table
![plugins-id](https://cloud.githubusercontent.com/assets/1172428/10861347/ea43d36c-7f7b-11e5-8291-941e25b17887.jpg)

Unfortunately I've noticed this just now, so I can't really tell when first happened (but I guess indee after the Github update process).

Simply removing the row from the database should fix this I think, but maybe is something to do with your internal functioning, so I'm reporting here this first to know your opinion.

Thank you!

**Comment by trob** [comment]
I don't think it's Fabrik (only) but Joomla.
I can't see your plugins but the birthday plugin.
BUT additionally on my site there are
![image](https://cloud.githubusercontent.com/assets/1045355/10862688/1553f1c2-7fb3-11e5-8dc1-6fd98fc8e72a.png)
(my installed languages)

A GitHub update is just copying files, did you do the "Post GitHub steps", ie. "Refresh Cache" in Extension manager?
Maybe Joomla is doing something wrong there or the xml files are not 100% correct.

**Comment by UberGruber** [comment]
Thanks Trob,
yes I've cleared the cache, and tried again, no noticeable results.

> Maybe Joomla is doing something wrong there or the xml files are not 100% correct.
>
> You can find the entries in #_menu, menutype=main

Can't understand fully what you mean, I've tried looking at the .xml files of the "password" and "notes" plugins but haven't noted nothing wrong. What should I look for exactly?

**Comment by trob** [comment]
"Maybe Joomla is doing something wrong there or the xml files are not 100% correct.
You can find the entries in #_menu, menutype=main"

This was "thinking loudly" what I've found - for Hugh and Rob for looking further.

If you want to get rid of the Component entries you can delete them from the #_menu table (not the #_extensions table; but always backup before touching such core tables).

Next time better open a thread, the issues are for confirmed Fabrik issues.

**Comment by UberGruber** [comment]
Tthanks for your input! 
Sorry, I thought was better to open a possible technical issue here instead of post on forum. Should I open a post on the forum then? or I leave this here?

**Comment by pollen8** [comment]
pretty sure this is nothing to do with us. That menu rendering is dealt with in Joomla. Our plugin declarations in the db are correct. 
I would suggest  reporting this on the Joomla project

**Comment by UberGruber** [comment]
Ok I see, I'll forward this to them then!
