### ISSUE TITLE
JS error in every form

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1565]
With Protostar
"NetworkError: 403 Forbidden - http://localhost/j33/%3Ci%20class=%22icon-spinner%20icon-spin%22%20%3E%3C/i%3E
or
"NetworkError: 404 View nicht gefunden ...x]: form, i, fabrikView - http://localhost/j33/fabrik-user-reg/form/17/%3Ci%20class=%22icon-spinner%20icon-spin%22%20%3E%3C/i%3E"

With purity_iii
"NetworkError: 403 Forbidden - http://localhost/j33/%3Cspan%20class=%22fa%20fa-spin%22%20%3E%3C/span%3E"

It isn't related to a special element or tooltip....

Maybe this is also the reason here
http://fabrikar.com/forums/index.php?threads/odd-text-in-registration-form.42487/

**Comment by cheesegrits** [comment]
What pages are you seeing those one?  I thought I'd fixed that with this commit:

https://github.com/Fabrik/fabrik/commit/7dd52ff3d57684cfc8c8830fae3f4efc51ed2c36

   -- hugh

**Comment by trob** [comment]
Sorry, outdated overrides
