### ISSUE TITLE
list layout: headers don't wrap

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1569]
https://github.com/Fabrik/fabrik/commit/2feff0d7befd981c89fee1983da8e648f7a24377
fabrik.css
+/** Prevent line breaks between sort icon and heading label in lists */
+
+.heading.fabrik_ordercell {
+	white-space: nowrap;

not good; this prevents any wrap in header labels and so expanding list width if you have some descriptive list headers

BTW: fabrik_ordercell is added even if the element is not set to "enable ordering"

**Comment by Sophist-UK** [comment]
IMO the correct way of prevent a line break at a specific point between sort icon and heading label is to use a non-breaking space &nbsp;.

I appreciate that this does not make it easy (or possible) to override using CSS, but that is nevertheless the correct way to stop a line break at a specific point.

**Comment by trob** [comment]
Not so easy because it's done with 
<span class="some-icon"></span>Header text

**Comment by Sophist-UK** [comment]
`<span class="some-icon"></span>&nbsp;Header text` or 
`<span class="some-icon">&nbsp;</span>Header text`

Simples.

**Comment by Sophist-UK** [comment]
Hmmm... on reflection I may have been talking b****cks.

I am not sure whether you get a line-breaking point between a span and text if there is no space between them. Is there a space inserted by Fabrik?

**Comment by trob** [comment]
meanwhile it's
3.4.1:
fabrik_ordercell is still added to ALL headers, no matter if the element's "Enable odering" is set or not
and
.heading.fabrik_ordercell, .fabrikTag {
    white-space: nowrap;
}
is preventing long headers from wrapping

A possible solution: instead of
<i class="icon-menu-2 " data-isicon="true"></i>Labeltext aa bb cc
do
<i class="icon-menu-2 " data-isicon="true" style="font-style:inherit">
abeltext aa bb cc</i>

**Comment by pollen8** [comment]
personally I think this is a matter of choice, not a bug. I've had people argue the other way round. That wrapping the titles looks odd as well.
Ultimately I would suggest that its managed in the template css.

**Comment by trob** [comment]
Seams to be fixed https://github.com/Fabrik/fabrik/commit/85fb3b1fe530c1e0e6b7d3f3ddc78687477438c7
