### ISSUE TITLE
ORDER BY DESC ignored if element is used in GROUP BY

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1571]
A group_by_element xx is always added with
ORDER BY xx ASC in the first place of the ORDER BY query
even if it's defined as DESC in list's Data tab

In this case the query is
ORDER BY xx ASC xx DESC (+maybe other "Data" tab ordering) (+maybe "Group by" tab ordering)
which is ignoring the 2nd part

http://fabrikar.com/forums/index.php?threads/problem-in-my-list-after-3-3-4-fabrik-version-upgrade.42530/

**Comment by trob** [comment]
details see http://fabrikar.com/forums/index.php?threads/problem-in-my-list-after-3-3-4-fabrik-version-upgrade.42530/#post-217207

**Comment by cheesegrits** [comment]
Should be fixed by https://github.com/Fabrik/fabrik/commit/9931a015616e63ba36403d95f90f70d3837a0a8e
