### ISSUE TITLE
jlayouts for specific elements

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1580]
WIKI says
You will need to create a folder in your active template directory:
/templates/{current-joomla-template}/html/layouts/com_fabrik/elements/{tablename___elementname}

but this is not working
Tested with fabrik-element-fileupload-image.php

/templates/{current-joomla-template}/html/layouts/com_fabrik/fabrik-element-fileupload-image.php
is working fine

**Comment by felixkat** [comment]
The Joomla documentations suggests

/templates/{current-joomla-template}/html/com_fabrik/

opposed to our current

/templates/{current-joomla-template}/html/layouts/com_fabrik/

Any reason we use the 'layouts' directory within the template path?

**Comment by pollen8** [comment]
/templates/{current-joomla-template}/html/com_fabrik/ would be for component view overrides, not for layouts
The wiki was incorrect. The path should be
/templates/{current-joomla-template}/html/layouts/com_fabrik/element/{tablename___elementname}
also note ive added:

/templates/{current-joomla-template}/html/layouts/com_fabrik/elements

to the layout paths so you can add a layout to override all plugin fields of the same type

**Comment by felixkat** [comment]
Cool, thanks for clearing that one upm was confusing the hell out of me.  :+1:
