### ISSUE TITLE
dbjoin frontend add option not working for radio rendering

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1587]
TypeError: opt is undefined
http://localhost/j33/plugins/fabrik_element/databasejoin/databasejoin.js
Line 219

**Comment by felixkat** [comment]
Confirmed

**Comment by trob** [comment]
ok meanwhile
remaining notice fixed via https://github.com/Fabrik/fabrik/commit/87ffb504738dac39836eeb1c86ba1be4762c75c0
