### ISSUE TITLE
Content Plugin - 'default' needs to be changed to 'bootstrap'

### ISSUE THREAD

**Issue by felixkat** [Fabrik/fabrik#1588]
Default templates used to be in a default folder, they are now in a 'bootstrap' folder.  Found two references that need to be changed.

Will create pull request.

**Comment by pollen8** [comment]
hey Paul did you have time to make a PR?

**Comment by felixkat** [comment]
Not yet but I will, I can only see two places the code needs changing.  Just need to finalise my Linux build and then I'll start firing the PR's off.  :+1:

**Comment by felixkat** [comment]
This was causing an issue that I can no longer recreate!!  Will re-open if it appears again.
