### ISSUE TITLE
"last run" time in sheduled task

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1590]
If editing a cron job the "last run" date is showing only day without time, so after save the time is reset to 00:00

**Comment by felixkat** [comment]
Changing the cron.xml seems to fix this one.

    		<field name="lastrun"
			type="calendar"
			class="input-medium"
			label="COM_FABRIK_CRON_FIELD_LAST_RUN_LABEL"
			format="%Y-%m-%d %H:%M:%S"/>

Add in the format parameter on the last line and add the Hour, Minute, Second.  

I've only done a quick test, let me know if it works before we create a patch.

**Comment by trob** [comment]
Good hint. It's better, but...

list view is showing UTC time (I assume; my local server time is UTC+1)
form view is showing UTC+1
after save list view is showing UTC+1 and then form view UTC+2 etc...

So it's not only the format (which is fixed with your patch) but also timezone handling.

**Comment by felixkat** [comment]
I've had a quick look at the code and the query is producing date & time, that is to say the 'time' isn't being truncated anywhere.  So it's is the actual display of the time that was missing which the XML modification may fix.

Is this something that used to work or has it always been this way, I've seen a lot of commits with the calendar so wasn't sure if it was related.

So if I have this correct you should be seeing UTC+1 which is the stored value +1.  With the XML change everytime you go in and save it add's  +1   ?

**Comment by felixkat** [comment]
Having looked at some other Joomla xml's it seems there is another missing bit we need.  `filter="user_utc"`.  Haven't tested but it looks likely to what is required.

        <field name="lastrun"
        type="calendar"
        class="input-medium"
        label="COM_FABRIK_CRON_FIELD_LAST_RUN_LABEL"
        format="%Y-%m-%d %H:%M:%S"
        filter="user_utc" />

Can you confirm @trob ?

**Comment by trob** [comment]
No, this doesn't help.
filter="user_utc" is the default
https://docs.joomla.org/Calendar_form_field_type

setting it to server_utc or setting explicitly my user time zone to "zurich" (should be default if not set and server timezone is set to "zurich") doesn't schange anythin:
cron list is showing DB time (utc), cron edit is showing +1 hour, after save it's showing +an other hour (and DB time has incremented)

Is Fabrik doing some extra date/time handling? Or not saving via JDate?
I've checked with article dates, there all is ok (showing local times in articles, UTC in database, saving correctly), so it seems to be a Fabrik issue

**Comment by felixkat** [comment]
Okay I will look into it further, I'll have to setup a seperate enviroment in a different time zone to test.  

Thanks for the update.  :)

**Comment by cheesegrits** [comment]
I just set it to utc and people can figure it out.  :)

I just wanted to get the time part showing.
