### ISSUE TITLE
scheduled task and new "Query secret"

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1591]
Also a wrong "Query secret" is setting a new "last run time" (but correctly nothing is executed).

So if somebody is trying to run with a wrong password or if all (other) scheduled tasks are run with fabrik_cron=1 the last runtime is set (and so  the following correct run inside the next "period" won't be executed)

reschedule() is running even with wrong password but I can't manage to get any output via var_dump, exit or $app->enqueueMessage.
In fabrik_logs there's always a new entry
8,Undefined index: q,C:\xampp54\htdocs\j33\components\com_finder\router.php,67

Is it intentionally that the shudownHandler is rescheduling in case of an error?

**Comment by felixkat** [comment]
Whilst on the subject of Crons......

As we have a 'secret' option would it be feasable to manually run a cron from the frontend?  Kind of like a 'run now' option which overrides the cron schedule.  If we made it compulsory that it would only run whilst using the Query secret I can't see any negatives.

Views?

**Comment by felixkat** [comment]
Is this issue still current troester, I see a few changes recently.

**Comment by trob** [comment]
Yes, just tested with an email plugin
The mail is correctly not sent if the Query secret is wrong
but "Last run" is always updated even if QS is wrong.
With wrong QS the log is showing 

> 2048,Non-static method DojoLoader::getInstance() should not be called statically, assuming $this from incompatible context,C:\xampp54\htdocs\j33\plugins\system\dojoloader\dojoloader.php,30
No idea where this is coming from

With correct QS the log is showing

> 8,Undefined property: PlgFabrik_ElementYesno::$tmpl,C:\xampp54\htdocs\j33\plugins\fabrik_element\yesno\yesno.php,76
I assume in both cases it's logging the last error message...

**Comment by cheesegrits** [comment]
Anything which isn't due to run, won't do anything ... it won't be in the query results where we load everything due to run, so it won't log, we won't even check the querystring, etc.

I can't duplicate the issue with last run when the query string is wrong.  It correctly "continues" to the top of the main loop that processes all plugins due to run, and never executes the reschedule() towards the bottom of the loop.

**Comment by pollen8** [comment]
if Hugh cant replicate I will close for now, please re-open if its still an issue
