### ISSUE TITLE
Cascading Dropdown plugin problem with Radiolist rende

### ISSUE THREAD

**Issue by rodolphopedra** [Fabrik/fabrik#1598]
When you have more than one cascading elements, only the first put the foreign key to de database directly. The others cascading elements puts the ZERO (0) value. With Dropdown render this issue do not fails, only with radiolist.
Sorry my english!

Joomla 3.4.5
Fabrik 3.3.5, with github last update (15/12/2015)

**Comment by felixkat** [comment]
So...

Dbjoin  CCD1, (radio),  CCD2, (radio),

CCD2 will put Zero as value?

**Comment by rodolphopedra** [comment]
Yes.

When render as Combobox the value is correct. Only occurs error when render as radio list.

**Comment by felixkat** [comment]
Can you perform a Git update and test this again please.

I see a few changes in the last 3 weeks so this may have been fixed.  If not I'll have a look.

**Comment by felixkat** [comment]
No response from OP so assumed to be working now.
