### ISSUE TITLE
Date element placeholder not translated

### ISSUE THREAD

**Issue by giruf** [Fabrik/fabrik#1604]
In a Date element in form view the placeholder string, which is configured in language overrides, is not translated.

I solved this modifing the file "/plugins/fabrik_element/date/date.php"
at line 302:

$calOpts['placeholder'] = $placeholder;

modified to:

$calOpts['placeholder'] = FText::_($params->get('placeholder'));

**Comment by trob** [comment]
Added https://github.com/Fabrik/fabrik/commit/d558e90c735e04fb4819caf09070755eb8f81c8f
Better use a pull request next time.
