### ISSUE TITLE
form success message is not showing correctly

### ISSUE THREAD

**Issue by giruf** [Fabrik/fabrik#1605]
The success message shown after clicking save on a form is translated correctly only once per session.
I have 2 language on my site, english and italian.,
I configured language overrides for the success message string for both languages.
So if I save the form while using english it will show the english message correctly.
But if at this point I switch to italian and I save the form it will show again the english message.

The same happens If i first save the form in Italian and then I switch to english, it will show Italian message for both languages.

I solved the problem for the moment modifying file /components/com_fabrik/models/form.php:

commented out around line 5120:
//$sMsg = $this->session->get($context . 'msg', array($msg));

and added immediately after:
$sMsg = "";

**Comment by felixkat** [comment]
Would it be normal for somebody to switch languages during a session?

The session is probably storing your language settings and possibly doesn't expect for somebody to change language during a session.  

What happens if you log out and login, does it show the correct messages?

**Comment by felixkat** [comment]
No response from OP so cannot confirm the issue.
