### ISSUE TITLE
Checkbox using 100% cpu resources for 600 +ms when clicked  (IE11 and IE10 and IE9)

### ISSUE THREAD

**Issue by manuelTop** [Fabrik/fabrik#1610]
fabrik  3.4
joomla 3.4.8 Stable  
template  protostar 

checkbox when filtering,  woking in slowmotion in IE and 100% cpu, no problem found in FF /  chrome
![checkbox](https://cloud.githubusercontent.com/assets/16426155/12039053/763a98b4-ae5d-11e5-99d0-798661bfe022.png)

**Comment by felixkat** [comment]
Can you provide more details of your setup \ filters etc so somebody can try and re-create this, or point us to a dev page?

**Comment by manuelTop** [comment]
Hi felixkat 
thanks for the interest
The setup is the most basic , I have 6 fields whom I filter via checkboxs  4 of them have 3 checkbox 1 got 10 checkbox  and 1 with 7 checkbox.

I populated the fields with abcdefg etc ....... to keep it simple and see from where the problem could come from,

from my research so far,  I suspect mootools, whom create events listeners .
if I disable mootools via the menu manager in joomla  the problem is gone, but with mootools disabled some other functions of fabrik stop working.

let me know if you need more information 
I am working on my laptop ( localhost ) so giving access will be some what difficult.

**Comment by JimboManiac** [comment]
Windows version please?

On 12/30/2015 10:08 AM, manuelTop wrote:
> I am working on my laptop ( localhost ) so giving access will be some 
> what difficult.


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by manuelTop** [comment]
Winows 7
