### ISSUE TITLE
list in details page

### ISSUE THREAD

**Issue by manuelTop** [Fabrik/fabrik#1615]
Hi every one , hope you all had a good festivities for this new year.

1) when I use {fabrik view=list id=4} in an article it work the full list is rendered without problem 

2) when I add {fabrik view=list id=4} in the default detail template is just returns "no record" but the pagination is rendered.

3) If I add {fabrik view=list id=4 test___size=1} in the default detail template all the items with size 1 will be rendered at the bottom of the detail page.

4) if I add {fabrik view=list id=4 test___size= test2___size} in the default detail template it returns no record but the pagination is rendered, for testing  I add {test2___size} in the default detail template  the value 1 is displayed correctly.

any idea would be welcome 

Thanks 

Windows NT X-PC 6.1 build 7601 (Windows 7 Business Edition Service Pack 1) i586  
Database Version  5.6.15-log  
Database Collation  latin1_swedish_ci  
PHP Version  5.5.8  
Web Server  Apache/2.4.7 (Win32) PHP/5.5.8  
WebServer to PHP Interface  apache2handler  
Joomla! Version  Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT  
Joomla! Platform Version  Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT  
User Agent  Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko 
Fabrik 3.4

**Comment by felixkat** [comment]
Can you try adding  layout=bootstrap i.e   {fabrik view=list id=4 layout=bootstrap}  Not sure if it will make a difference but it will eliminate something I was looking at the other day.

**Comment by manuelTop** [comment]
Thanks for the quik relpy Felixkat ,

I will try it right now , and revert.
Thanks again

**Comment by manuelTop** [comment]
Hi Felixkat 

good news and bad news 

The good news is by adding layout=bootstrap now the full list renders 

The bad news is that point 4 of my previous post remains 

if I add {fabrik view=list id=4 test___size= [test2___size] layout=bootstrap  } in the default detail template it returns no record but the pagination is rendered, for testing I add {test2___size} in the default detail template the value 1 is displayed correctly.

Thanks again

**Comment by trob** [comment]
Better open a thread in the forums.
Try to add clearfilters=1 or resetfilters=1

**Comment by manuelTop** [comment]
Dear Trob

Sorry , I thought to report a bug I should do it here ,
I tried your suggestions the problem remains the same , the filter is not been taken into account.
when i load the detail page.

if I add {fabrik view=list id=4 test___size= [test2___size] layout=bootstrap } in the default detail template it returns no record but the pagination is rendered, for testing I add {test2___size} in the default detail template the value 1 is displayed correctly.

If I add  {fabrik view=list id=4 test___size= 1 layout=bootstrap } in the default detail template it's working correctly.

Thanks in advance.
