### ISSUE TITLE
More than one field in mailto fields

### ISSUE THREAD

**Issue by HansLe** [Fabrik/fabrik#1617]
I discovered 2 bugs in Fabrik which I want to share with you so you can improve Fabrik. It has to do with two plugins when using comma separated addresses in the e-mail to field.

Plugins/fabrik_cron/email/email.php: change line 87 to “if (FabrikWorker::isEmail(trim($thisTo)))”
Plugins/fabrik_list/email/models/email.php: change line 495 to “ if (FabrikWorker::isEmail(trim($mailTo)))”

The suggested changes worked for me but maybe there are better solutions.

Regards,
Hans

**Comment by felixkat** [comment]
I can see what your code does but can you explain what errors you were seeing?

**Comment by HansLe** [comment]
I didn't get errors. When I used two placeholder fiels in the mail-to-field I got the message 1 e-mail sent 1 e-mail not sent. So only the first placeholder was used.

**Comment by felixkat** [comment]
Thanks, that should be enough to test with.

**Comment by felixkat** [comment]
Just to say I had a quick look at this but I cannot re-create any problems with spaces appearing in a comma seperated addresses, (assuming there is no spaces in between the addresses).

Having said that I don't see any harm put in a 'trim' but I'm curious as to why you are seeing this issue.

**Comment by pollen8** [comment]
thanks I've added those changes
