### ISSUE TITLE
Groups can't be reordered/added/removed in form settings

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1618]
http://fabrikar.com/forums/index.php?threads/f3-4-groups-not-reordering.42867/
http://fabrikar.com/forums/index.php?threads/problem-with-groups-ordering-after-update.42872/
http://fabrikar.com/forums/index.php?threads/groups-order-not-working-in-form-setings.42911/

This is the commit which is breaking the ordering
https://github.com/Fabrik/fabrik/commit/199a990570938e0ffa194b7a422c2236c1a28fbb

**Comment by advancn** [comment]
I am also having this issue, i attempted several times to move the groups up. I finally had to change the position of my fields as a work-around

**Comment by trob** [comment]
Solved with https://github.com/Fabrik/fabrik/commit/ed3f1ae4ef028b2e7ffac4fe4e5cee428be0c50b
