### ISSUE TITLE
Fabrik PHP7 J!3.5.0 beta2 beta

### ISSUE THREAD

**Issue by ghazal** [Fabrik/fabrik#1638]
Tested Fabrik 3.4.2 in php7 and  J!3.5.0 beta2 beta.
It uses Joomla\String\String which causes a Fatal error :
Fatal error: Cannot use Joomla\String\String as String because 'String' is a special class name in ...

I replaced it everywhere by :
Joomla\String\StringHelper just to get administrator back

Not sure it is the right solution but it helped.

Additionally, i got some :
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP
I replaced the names of functions with the same name as their class by  " __construct ".

Hope it helps.

**Comment by cheesegrits** [comment]
Thank you.

Yes, StringHelper is the "official" fix for that.  We'll have to figure out how to provide b/c with earlier J! versions though.

**Comment by pollen8** [comment]
this has been fixed. The only compatible way was to revert to using the deprecated JString class

**Comment by waqas07** [comment]
after installing fabrik i found error 
Fatal error: Class 'Joomla\String\StringHelper' not found in public_html/libraries/fabrik/include.php on line 180  i cant figure it out how can i solve this issue.

**Comment by ghazal** [comment]
Are you using the latest version : Fabrik 3.5 ?

**Comment by waqas07** [comment]
Yes latest although fine installation on another joomla

**Comment by trob** [comment]
Can you please post in the forums and mention exactly your setup: J! version, how did you install, which Fabrik version....

**Comment by waqas07** [comment]
i install that latest one from install from web option directly. although i tried on another site which is latest joomla version website its working there fine. then i updated joomla to latest version and then i become unable to even install fabrik. finally i deleted all files and uploaded backup of site and disable error reporting and then again now i will install by disabling error reporting.

**Comment by waqas07** [comment]
and now its again currupt site with installation. i deleted component fabrik manually from cpanel for admin and front for site working again and then i uninstall all fabrik plugins. but i cant able to uninstall main fabrik component.

**Comment by waqas07** [comment]
in fabrik forum?
