### ISSUE TITLE
Problem with Cascading dropdown rendering

### ISSUE THREAD

**Issue by Ivan4o0o** [Fabrik/fabrik#1645]
Hi, I have a cascading dropdown fields and when I choose a value that is in Cyrillic in the Watched field the cascading drop down doesn't show any options. When I searched in the SQL queries it looses the Id. 
Here is the query when it is in Latin (english):
```
 455 Query	SELECT DISTINCT(`plforms_repeat_load_depo`.`id`) AS value, `plforms_repeat_load_depo`.`address`AS text
FROM `clients` AS `plforms_repeat_load_depo`
WHERE `plforms_repeat_load_depo`.`id` = '654'
```

and when it is in Cyrillic
```
 455 Query	SELECT DISTINCT(`plforms_repeat_load_depo`.`id`) AS value, `plforms_repeat_load_depo`.`address`AS text
FROM `clients` AS `plforms_repeat_load_depo`
WHERE `plforms_repeat_load_depo`.`id` = ''
```

the same but with empty string for id (in my case).

**Comment by Sophist-UK** [comment]
Github issues are reserved for diagnosed bugs. If you want support, please raise this in the appropriate forum on the Fabrikar web site.

Thx.

**Comment by felixkat** [comment]
Closed as per above comment, will re-open if confirmed issue.
