### ISSUE TITLE
List column calculation sometimes has different # of decimals than list fields

### ISSUE THREAD

**Issue by kentanilsson** [Fabrik/fabrik#1649]
Depending on values in column the final summary line total sometimes is 101.12345678 instead of expected 101.11 . The field data format is 2 decimals. I can't find a place to set the summary format. It must be able to set the format for each column and there must be a global default.
In the left case shown the result should be 1181.97.

![screenshot from 2016-02-22 22 34 41](https://cloud.githubusercontent.com/assets/10948342/13233827/e601dc56-d9b5-11e5-805a-29249a1cc750.png)

**Comment by Sophist-UK** [comment]
Could be a bug that the formatting you specified is not being applied to the Total - and probably one that it easy to fix.

Can you please provide a screen shot for the definition of the Moms field?

**Comment by kentanilsson** [comment]
Nothing special. Normal mostly default settings. Datatype in DB is DECIMAL(12,2).
![screenshot from 2016-02-23 13 31 02](https://cloud.githubusercontent.com/assets/10948342/13251662/dd856f58-da31-11e5-85c5-e5b89d1d6af6.png)

**Comment by Sophist-UK** [comment]
Have you tried setting "Number Format" to "Yes" or putting an sformat string in the Format String box?

P.S. Please use the forums next time - Github issues are for logging identified bugs.

**Comment by felixkat** [comment]
Closing.  No response from OP and not a comfirmed issue.
