### ISSUE TITLE
Function getFieldValue of juser Fabrik Form plugin 3.4.2

### ISSUE THREAD

**Issue by Rinexpro** [Fabrik/fabrik#1651]
Hello everybody,

I'd like to get some help on an issue I just discovered.

I re-built a login form for Joomla 3 according to [this tutorial](http://www.betterliving.be/fabrik/remplacer-le-formulaire-d-enregistrement-de-joomla-partie-1.html). It is Joomla 2 in the tutorial but I did it on Joomla 3 with my installation of Fabrik 3.4.2. When I tried the form by creating an account from the front end, I got the following error message :
Fatal error: Call to undefined method PlgFabrik_FormJUser::getFieldValue() in /volume1/web/joomla/plugins/fabrik_form/juser/juser.php on line 427

Having a look at the file mentioned, it appears the method getFieldValue is not written in the file, causing an error at the first occurence line 427. I checked in the Fabrik 2 file of juser plugin and the function is there. It seems it has not been set in Fabrik 3. How to deal with that now ?

Thanks a lot for your help.

**Comment by trob** [comment]
Can you please post in the forums.

I assume you have a version mix: in Fabrik3.4.2 function getFieldValue IS in juser.php, it was moved to plgFabrik_Form in the recent GitHub.

So in the forum please mention exact Joomla and Fabrik versions (download, Joomla update, GitHub?)
How did you install juser? It's not part of the Fabrik core. It must be exactly the version of your Fabrik core installation.
