### ISSUE TITLE
No sort direction arrows in list header

### ISSUE THREAD

**Issue by ha5di** [Fabrik/fabrik#1666]
Hi,

I'm running 3.4.2 on Joomla 3.4.8 List sorting works, but no icons indicating sort order, just the underlined column label.

Béla

**Comment by trob** [comment]
Can you please post in the forums.
GitHub issues are for confirmed general issues.
Yours is pretty sure a Joomla template issue.

**Comment by ha5di** [comment]
Thanks for the hint. You are right, changing template arrows are visible, I will dig in this direction.
