### ISSUE TITLE
Blank screen after fabrik update

### ISSUE THREAD

**Issue by nikosfa** [Fabrik/fabrik#1672]
I'm continuously getting blank screen after uploading and extracting latest github Fabrik zip. 
I'm forced to pull latest site's back up in order to recover. 
No errors are reported just blank screen. My resources are showing ok. What can be going wrong. I did updates in the past hundred times, without any problem.

**Comment by trob** [comment]
don't update at the moment

**Comment by nikosfa** [comment]
Is it ok to update now from GitHub ?

**Comment by trob** [comment]
Depends on where you blank screen was coming from...
Update is ok on my site now.

**Comment by nikosfa** [comment]
Thank you

**Comment by pollen8** [comment]
closing as this doesn't provide a thorough report on how to replicate a bug. A blank screen is always a sign that error reporting is not set to max, so without that error report we can not fix the issue. Feel free to re-open an issue with a complete error report and steps to take to replicate the bug if it still persists
