### ISSUE TITLE
Date Element decreases date 

### ISSUE THREAD

**Issue by nikosfa** [Fabrik/fabrik#1673]
Joomla! 3.3.6 Stable
Fabrik ver. 3.3.3
Date Element ver. 3.3.3

Date Element decreases date by one (1) day after saving the form, using "UTC" time setting. Using "Local" time setting seems to work ok.

**Comment by trob** [comment]
Can you please post in the forums.
Recent Joomla is 3.4.8, recent Fabrik 3.4.2
nobody is reporting such an issue on standard date elements

**Comment by nikosfa** [comment]
Hi, 
I just wanted to report an issue. Here is the relevant link in forums http://fabrikar.com/forums/index.php?threads/workaround-fullcalendar-new-entry-startdate-starts-at-the-day-before-the-clicked-date.43095/

**Comment by pollen8** [comment]
The issue seems to have been resolved in the forum
