### ISSUE TITLE
requirejs errors on iframe window load

### ISSUE THREAD

**Issue by cheesegrits** [Fabrik/fabrik#1675]
Example, use the "Email" icon on a form ...

Uncaught Error: Script error for: fab/chosen-loader
Uncaught Error: Script error for: fab/tipsBootStrapMock
http://requirejs.org/docs/errors.html#scripterror

etc etc

**Comment by pollen8** [comment]
Is this still an issue after today's changes? What are the js debug
settings and are enhanched dropdowns enabled?
