### ISSUE TITLE
Form - Email Plugin - Plain Text Email

### ISSUE THREAD

**Issue by felixkat** [Fabrik/fabrik#1676]
As Per:-

http://fabrikar.com/forums/index.php?threads/email-spam-multipart-alternative-mime.43579/

Add the option of a plain text email.

**Comment by felixkat** [comment]
Just for reference email form plugin.

		// Always send as html as even text email can contain html from wysiwyg editors
		$htmlEmail = true;

**Comment by trob** [comment]
Should be here https://github.com/Fabrik/fabrik/commit/db34b8a1dae9796a1f2415a469643d687e3342b0
