### ISSUE TITLE
form pdf not loading

### ISSUE THREAD

**Issue by pollen8** [Fabrik/fabrik#1678]
Since j35 upgrade:
Warning: require_once(F:\Users\rob\PhpstormProjects\fabrik31x\public_html\libraries/joomla/document/html/html.php): failed to open stream: No such file or directory

**Comment by trob** [comment]
J3.5 has moved
 libraries/joomla/document/html/html.php
to
 libraries/joomla/document/html.php

but it seems the require isn't necessary at all: PDF in list and form is working fine on my site if 
require_once JPATH_LIBRARIES . '/joomla/document/html/html.php';
in
\libraries\joomla\document\pdf\pdf.php line 17
is just commented out

**Comment by cheesegrits** [comment]
When you say "needed in 3.4.8" do you mean the require_once?

**Comment by cheesegrits** [comment]
https://github.com/Fabrik/fabrik/commit/887959ad713ac38392a5715fe9c3edcb4af20419
