### ISSUE TITLE
Event.Mock.js error

### ISSUE THREAD

**Issue by nikosfa** [Fabrik/fabrik#1680]
Joomla 3.5
Fabrik: Latest github update

Javascript error

"NetworkError: 404 Category not found - http://www.site.com/media/com_fabrik/js/lib/Event.Mock.js?bust=1458827062"
Event.M...8827062
Error: Script error for: lib/Event.Mock
http://requirejs.org/docs/errors.html#scripterror
	...=c[b]});return c}function C(b,c,d,g){c=Error(c+"\nhttp://requirejs.org/docs/erro...

**Comment by felixkat** [comment]
Please report problems in the forums, once confirmed we can open an issue.
