### ISSUE TITLE
'save partly filled forms' not working on new records

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1681]
Seems it has stopped working some time ago (did it ever on Fabrik3.1+?) , I've tested with J!3.4.8 + Fabrik3.4.2, too
Same behaviour as with J!3.5 and Fabrik3.4.3

http://fabrikar.com/forums/index.php?threads/multipage-form-not-saving.43601/#post-222995

It's only if adding a new record, ok if editing an existing one 

Click "Add" 
After leaving the form the data is correctly saved in fabrik_form_sessions
on re-enter (i.e. clicking "Add" once more) the message is shown correctly (but no clear button) but
there's NO data in the elements of the hidden page (also before clicking "previous", which will trigger validation and "page saving")

**Comment by pollen8** [comment]
Could you retest this one please? 
I've fixed the clear button issue not showing and for me the multipage data does save and is shown when creating a new record (tested both front and back end)

**Comment by pollen8** [comment]
ah I see @cheesegrits fixed the main issue and forgot to close this ticket - I'll close and if there are more multi page issues lets open a new ticket
