### ISSUE TITLE
email error and Joomla3.5.1

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1692]
J!3.5.1 has change it's email handling
tested with form email plugin
1. errors during $mail->sendMail won't return any error code but create a system error message and redirect to (??history??), so if a first form email is failing anything else is stopped, it's returning to list view and showing the error message. It's not Fabrik doing this (any debug + exit directly after $mail->sendMail isn't run, it's return from inside $mail->sendMail)

2. empty attachements aren't longer tolerated, so any fileupload element with "email file=yes" will break the form email plugin if the fileupload is empty

http://fabrikar.com/forums/index.php?threads/error-message-pop-up-whenever-a-form-is-filled-and-saved-email-form-plugin.43768/
http://fabrikar.com/forums/index.php?threads/joomla-3-5-1-update-breaks-email-plugin-w-attachments.43736/

**Comment by cheesegrits** [comment]
Can you test ...

https://github.com/Fabrik/fabrik/commit/e57659f626f2cb422bfee0956d95cef43ce8997b

... which should fix this

**Comment by pollen8** [comment]
@trob did Hugh's fix clear up this issue?

**Comment by pollen8** [comment]
closing for now - if its still an issue please reopen
