### ISSUE TITLE
PHP7 issues

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1693]
deprecated constructors...
modules\mod_fabrik_tagcloud\helper.php on line 47
plugins\system\fabrikcron\fabrikcron.php on line 26
plugins\content\fabrik\fabrik.php on line 23

**Comment by trob** [comment]
element_raw fetching a dbjoin label in a calc element (only 1st run of 3 runs "on save"; the result of this run doesn't seem to be used but it may break e.g. MySQL queries used in the calc and relying on the value)

See http://fabrikar.com/forums/index.php?threads/calc-element-not-using-correct-placeholder.43688/page-2

**Comment by pollen8** [comment]
first issues are fixed in the develop branch, ill create a new issue for the second thing
