### ISSUE TITLE
fullcalendar issues

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1701]
no calendar shown
![image](https://cloud.githubusercontent.com/assets/1045355/14849411/226ab970-0c73-11e6-8339-23aacc207b65.png)
with latest joomla3 and dev branch (php5.4 and php7)
with joomla3 branch additionally 
Warning: array_unshift() expects parameter 1 to be array, null given in C:\xampp54\htdocs\j35\components\com_fabrik\models\list.php on line 6343

calendar is ok with build343 branch

**Comment by pollen8** [comment]
This should have been fixed a couple of days ago with 
https://github.com/Fabrik/fabrik/commit/bacf8f389388f08bc2800562062a5dd82e081c9a
the offset error no longer matches the list models line numbers - can you confirm if its still an issue and I'll reopen
