### ISSUE TITLE
Old version of SimplePie in joomla throwing errors in Fabrik

### ISSUE THREAD

**Issue by ghazal** [Fabrik/fabrik#1709]
hi,
looks like joomla is still using SimplePie v. 1.2 while it evolved to 1.4.
So Fabrik is throwing the usual error, like :
`Deprecated: Non-static method SimplePie_Misc::get_element() should not be called statically, assuming $this from incompatible context`
when a function is not "public".

What is your advice ?

Myself, I'd replace /libraries/simplepie/simplepie.php
by its equivalent here :
https://github.com/simplepie/simplepie/blob/master/library/SimplePie.php

What do you think ?

**Comment by ghazal** [comment]
Someone from the dev team  should read this :
Pull Request #8735 · joomla/joomla-cms -> 
https://github.com/joomla/joomla-cms/pull/8735#issuecomment-217634470

**Comment by pollen8** [comment]
hello,
how can this be replicated in our code?

**Comment by pollen8** [comment]
no reply - closing the issue
