### ISSUE TITLE
fullcalendar ignoring time zones on dblclick add

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1710]
from + to date are set to "store date as UTC"
doubleclick in calendar on 8am is opening the form with 'from date' = 06:00
(my timezone MEZ = UTC +2)
This issue is the same with build343 or joomla3 branch.

Seems it's doing timezone calculations for the "clicked" time instead of just taking it.

After saving it's "correct"/consistend in calendar/list/form view (6:00) and DB (4:00)

**Comment by trob** [comment]
I think there mustn't be a time zone conversion in addEvForm
plugins\fabrik_visualization\fullcalendar\controllers\fullcalendar.php (around line 162 and 182)

Times for setting dates in form URLs are local times, not UTC times

**Comment by trob** [comment]
It's still getting the wrong time, depending on "default to current" settings (which shouldn't do anything if a default is set otherwise??)
UTC + default to current=no: --> it's fetching the correct time from dblclick in calendar

UTC + default to current=yes: --> it's showing 2hours off (which is MEZ to UTC offset)
e.g. I click at 5pm (language settings are still not working), the form is showing 19:00

Same with the "to-date": 
with default to current=no: 17:15
with default to current=yes: 19:15

**Comment by pollen8** [comment]
try again please?
