### ISSUE TITLE
Fabrik does not create element's properties at creation in DB

### ISSUE THREAD

**Issue by fodinabor** [Fabrik/fabrik#1726]
Hey,
I'm using Fabrik 3.4.3 and a colleague just created a new list and created some new elements for this.
The problem we had is, that those new created elements had some params missing in the `params` column in `fabrik_elements`.

Those were `"placeholder":"","password":"0","maxlength":"255","disable":"0","readonly":"0","autocomplete":"1","speech":"0","bootstrap_class":"input-medium","text_format":"text","integer_length":"11","decimal_length":"2","field_use_number_format":"0","field_thousand_sep":",","field_decimal_sep":".","text_format_string":"","text_input_mask":"","render_as_qrcode":"0","guess_linktype":"0","link_target_options":"default","rel":"","link_title":"",`.

This lead to the fields in the form not being editable as the `maxlength`  was set to `0`. When opening the element in the backend and just saving the element once adds the needed params.    
I think these params should be set as default in the db from creation time, shouldn't they?

**Comment by cheesegrits** [comment]
Yes, they should, and on my test servers, they do.  Can you replicate this?

**Comment by fodinabor** [comment]
I had been able ... but no longer - works fine now..
