### ISSUE TITLE
popup issues

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1733]
Latest Git:

The dbjoin frontend add popup is popping up centered on the screen correctly.
But after the form has loaded screen is moving to the top of the original site and so the popup is vanishing at the bottom.
You have to scroll down to see it again (at least meanwhile it's possible again to scroll).

Related data popup is still breaking other buttons on the site
http://fabrikar.com/forums/index.php?threads/ajaxfied-links-are-breaking-other-buttons-on-the-site.44105/

**Comment by trob** [comment]
This may be related, too
http://fabrikar.com/forums/index.php?threads/popups-problems-after-git-update.44161/

**Comment by cheesegrits** [comment]
https://github.com/Fabrik/fabrik/commit/1cb75ac4a084aaffb839b6c77f78dab05b57baa1

**Comment by trob** [comment]
To add to this selection
fileupload crop
http://fabrikar.com/forums/index.php?threads/problem-fileupload-crop-window-urgent-problem-on-multiple-sites.44178/#post-226620

frontend add
frontend select
http://fabrikar.com/forums/index.php?threads/popups-problems-after-git-update.44161

email
http://fabrikar.com/forums/index.php?threads/e-mail-pop-up-box-collapses-when-right-scroll-bar-is-used.44180/

**Comment by cheesegrits** [comment]
I can't replicate the "still scrolling to the top", after this commit:

https://github.com/Fabrik/fabrik/commit/1cb75ac4a084aaffb839b6c77f78dab05b57baa1

... which definitely fixed it for me.  Can we make sure the OP definitely updated JS (including minified) and flushed cache, etc.

Which "email popup box"?

**Comment by trob** [comment]
Yes, frontend add and select are ok now.

email: I assume list plugin.
Just tested: 
email popup is not centered on the screen but on top of the site.
It's showing two scrollbars on the right site, one on the bottom (with wysiwig editor where the toolbar doesn't fit into the window)
If you try to move the popup all content is vanishing.
Not exactly the same behaviour as in the thread but sounds related.

**Comment by trob** [comment]
> email popup is not centered on the screen but on top of the site (so you have to scroll up to see it at all)
this one is coming from the commit https://github.com/Fabrik/fabrik/commit/0d62c01a5874e2c4d9bb3a786297d9fd64049ef5
It seems the email popup is positioning different from the other popups

**Comment by cheesegrits** [comment]
Ack phffft.  Seems like some popups are relative and some are absolute.  undone that commit.  Working on it.

**Comment by cheesegrits** [comment]
OK, imma need an assist from @pollen8

**Comment by pollen8** [comment]
can we test the changes I made today please?

**Comment by trob** [comment]
Frontend add/select popups are ok.
Select is not working if your are navigating to page 2,3... in your list but I don't know if this was working before.

List email plugin popup is displayed correctly, too. It's also showing the WYSIWYG editor.
BUT: it doesn't send the text from in this editor window, it's only sending the original message defined in the plugin setup.

**Comment by cheesegrits** [comment]
I fixed a few issues with the refactored list email plugin, seems to work OK now.

**Comment by trob** [comment]
hmm, it's still ignoring any change made on the default message shown in the WYSIWYG editor

**Comment by trob** [comment]
opening a new issue for the resting ones
