### ISSUE TITLE
WYSIWYG text editor not loading in ajax modals

### ISSUE THREAD

**Issue by pollen8** [Fabrik/fabrik#1738]
Due to the move over to using format=partial the head with the editor initialization code is not loaded.
Suggest attempting to either

- recreate the editor load js inside our code (brittle, and what about different editors)
- See if we can not temporarily get the document head in the partial document, extract the editor js and then re-remove the head.

**Comment by cheesegrits** [comment]
As per discussion in Skype, I think the only real solution is to add a document type for 'partial',in which we grab anything from the script head, and prepend it to the body.

I've started on this locally, still working on getting my head round the best way to do it.

**Comment by trob** [comment]
So this is the reason for "hmm, it's still ignoring any change made on the default message shown in the WYSIWYG editor" in https://github.com/Fabrik/fabrik/issues/1733  ?
