### ISSUE TITLE
ajaxfied links: not working for details view

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1749]
the form is shown in a popup
the details view is opening like non-ajaxfied

BTW: why does the form link contains listid=x, the details link doesn't?

**Comment by cheesegrits** [comment]
Works fine for me, and no listid on the URL.

Have you overridden the listactions/fabrik-view-buitton.php somewhere?

**Comment by trob** [comment]
Oh yes, sorry, some old layout stuff.
I really shouldn't do any custom (css, layout) stuff which won't be "reset" with a Github update) in the original bootstrap template
