### ISSUE TITLE
Delete buttons don't work when inserting multiple inline lists in an article (Content plugin)

### ISSUE THREAD

**Issue by David-Gil** [Fabrik/fabrik#1790]
My environment:
Fabrik: 3.5.1
Joomla: 3.6.2
Mysql: 5.7.15
PHP: 7.0.8

When there is more than one inline list in an article (via the content plugin) the delete buttons don't work and a message box appears: "Select some rows for deletion".

Despite selecting the rows, rows don't get deleted.

When only one inline list exists in an article, rows can be deleted normally and the whole list can be emptied.

I found this 2012 forum page where this same problem was talked about: http://fabrikar.com/forums/index.php?threads/select-some-rows-for-deletion.25815/

In that page @troester said this bug was already fixed in the github version. Somehow it has come back.

**Comment by trob** [comment]
Please post in the forums.
Are you using different lists (different listids) or the same list with e.g. different filtering?

**Comment by David-Gil** [comment]
> Please post in the forums.

Should I repost this issue in the forums?

Anyway, I will next time.

> Are you using different lists (different listids) or the same list with e.g. different filtering?

I'm using the same list with different filterings.

**Comment by David-Gil** [comment]
This isn't actually a bug, but a misunderstanding. I thought that lists were db tables, but they actually are interfaces to the db tables. One cannot have the same inlined list multiple times in the same article, delete buttons don't work. Therefore, multiple lists can be created (copied from the original) which point to the same db table. They can be unlinked from the parent list and work the same as an independent list. That way, one can inline in the same article different lists (pre-filtered differently) pointing to the same table.

Question answered in the forum:
http://fabrikar.com/forums/index.php?threads/delete-buttons-dont-work-when-inserting-multiple-times-the-same-inline-list.45331/
