### ISSUE TITLE
The form display code instead of showing the jpeg image

### ISSUE THREAD

**Issue by snesedson** [Fabrik/fabrik#1795]
The form displays code instead of showing the jpeg image

Only happens in some jpeg files and not in jpg files.

Element fileupload show this.
DLfwTwqYxFH5McXZgWtF1pXJXgbPmZckxBFffphk9r1c82DtdN.jpeg&quot;,&quot;params&quot;:&quot;{\&quot;rotation\&quot;:0,\&quot;scale\&quot;:100,\&quot;imagedim\&quot;:{\&quot;x\&quot;:200,\&quot;y\&quot;:200,\&quot;w\&quot;:843,\&quot;h\&quot;:1500},\&quot;cropdim\&quot;:{\&quot;w\&quot;:200,\&quot;h\&quot;:100,\&quot;x\&quot;:200,\&quot;y\&quot;:200},\&quot;crop\&quot;:false,\&quot;modalId\&quot;:\&quot;fileupload-modal-solicitao_de_assistncia_tc___comprovante_de_compra-widget-mocha\&quot;,\&quot;quality\&quot;:0.9,\&quot;mainimagedim\&quot;:{\&quot;x\&quot;:200,\&quot;y\&quot;:200,\&quot;w\&quot;:843,\&quot;h\&quot;:1500}}&quot;}]

I am using ajax upload

**Comment by snesedson** [comment]
Console show this error in javascript

**Uncaught Error: Syntax error, unrecognized expression:** #alreadyuploaded_24_[{&quot;file&quot;:&quot;\/comprovantes\/t5xxnG1Dj3fwBkq723s9Ps44Y3vhCPG6ZdNv5GH0H5xHmrdnL9.jpeg&quot;,&quot;params&quot;:&quot;{\&quot;rotation\&quot;:0,\&quot;scale\&quot;:100,\&quot;imagedim\&quot;:{\&quot;x\&quot;:200,\&quot;y\&quot;:200,\&quot;w\&quot;:843,\&quot;h\&quot;:1500},\&quot;cropdim\&quot;:{\&quot;w\&quot;:200,\&quot;h\&quot;:100,\&quot;x\&quot;:200,\&quot;y\&quot;:200},\&quot;crop\&quot;:false,\&quot;modalId\&quot;:\&quot;fileupload-modal-solicitao_de_assistncia_tc___comprovante_de_compra-widget-mocha\&quot;,\&quot;quality\&quot;:0.9,\&quot;mainimagedim\&quot;:{\&quot;x\&quot;:200,\&quot;y\&quot;:200,\&quot;w\&quot;:843,\&quot;h\&quot;:1500}}&quot;}]

**Comment by snesedson** [comment]
I identified that only the error occurs when the confirmation plugin is enabled.

**Comment by cheesegrits** [comment]
Yes, there are some known issues with the confirmation plugin with certain element types.  No fix is planned for this.

**Comment by snesedson** [comment]
The Confirmation Plugin is converting quotation marks to & quot and  saving in the database. Any idea how I can fix this?

**Comment by snesedson** [comment]
I simply corrected using a PHP Form Plugin with this simple code:

<?php

// Check to ensure this file is included in Joomla!
defined('_JEXEC') or die();

	
$string =	$formModel->formData['upload field name'];

$string = str_replace("&quot;",'"', $string);

$formModel->updateFormData('upload field name',$string , true, true);


?>
