### ISSUE TITLE
Joomla3.7 stuff

### ISSUE THREAD

**Issue by trob** [Fabrik/fabrik#1803]
just collecting

Strict Standards: Declaration of FabTable::getFields() should be compatible with JTable::getFields($reload = false) in \administrator\components\com_fabrik\tables\fabtable.php on line 119

Notice: Undefined index: filter-conditions in \components\com_fabrik\models\list.php on line 5611
(in a list with required filter, filter element as dropdown; but filter is working)

**Comment by trob** [comment]
The usual "backend repeat group" Joomla issue.
Seems to be ok after copying classes/36 to classes/37 (at least with multiple form plugins)

**Comment by cheesegrits** [comment]
All those should be fixed in the new joomla37 branch

Plus issues with date element (and any use of the "old" date picker, which has been deprecated)

**Comment by trob** [comment]
Some more 3.7:
PDFs (domPDF from GtiHub) showing a lot of notices in
\libraries\joomla\document\pdf\renderer\head.php 
undefined index abc in line 118,119,123,155,159,163

It seems this head.php is pretty much outdated.
I did test e.g. fabrikfeed or partial.

BTW: 
If you can add "Fabrik" documents like fabrikfeed and partial why can't you add fabrikpdf instead of pdf?
This would prevent conflicts with e.g. phoca pdf (which is overriding the Fabrik one or vice versa)

**Comment by trob** [comment]
Joomla3.7 and Fabrik3.6 (no GitHub):

PDF:
PDFs are only working if Debug PDF is set to YES and than back to NO one time. (Not necessarily a Fabrik3.6 issue, I think this has been reported before)
PDFs (domPDF from GitHub because it's not in the download area) showing a lot of notices in
\libraries\joomla\document\pdf\renderer\head.php
undefined index abc in line 118,119,123,155,159,163

Editing list settings:
trying to leave a text field with RETURN is opening the "search all element" setting popup

Additional plugins from download:
Some are not published after installing (e.g. yesno)
