### ISSUE TITLE
I can't open Joomla Administrator Page

### ISSUE THREAD

**Issue by drmkurt** [Fabrik/fabrik#1811]
I downloaded Fabrik 3.5.2 zip file and tried to install on the module manager page. A few minutes later, i took an error message: HTTP 500. After that, I tried to open administrator page, but i can't. It gives error message HTTP 500.

Please help me!

**Comment by trob** [comment]
Please post in the forums, the issues are for confirmed Fabrik issues only.
Give exact infos about your Joomla version, php version etc.
What do you mean with "install on the module manager page"?
If the error is really coming from the Fabrik installation it should help to disable the Fabrik system plugin directly in your database with some tool like phpMyAdmin.

**Comment by drmkurt** [comment]
Php 5.6
Joomla 3.4

Error Message:

Warning: require_once(/home/ipmsconf/public_html/ipms2018/administrator/components/com_fabrik/tables/fabtable.php): failed to open stream: No such file or directory in /home/ipmsconf/public_html/ipms2018/plugins/system/fabrik/defines.php on line 55

Fatal error: require_once(): Failed opening required '/home/ipmsconf/public_html/ipms2018/administrator/components/com_fabrik/tables/fabtable.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home/ipmsconf/public_html/ipms2018/plugins/system/fabrik/defines.php on line 55

**Comment by drmkurt** [comment]
Php 5.6
Joomla 3.4

Warning: require_once(administrator/components/com_fabrik/tables/fabtable.php): failed to open stream: No such file or directory in /plugins/system/fabrik/defines.php on line 55

Fatal error: require_once(): Failed opening required 'administrator/components/com_fabrik/tables/fabtable.php' (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /plugins/system/fabrik/defines.php on line 55

**Comment by trob** [comment]
It seems your Fabrik installation was incorrect/uncompleted...
Joomla3.4 is outdated.
As I've said:
disable the Fabrik system plugin directly in your database with some tool like phpMyAdmin.

Then update Joomla (to 3.6.5), download Fabrik again (in case you've corrupted the download file), install again.
Post the result in the forums.

**Comment by drmkurt** [comment]
Thanks a lot.
