### ISSUE TITLE
Show data  - Could not connect to database

### ISSUE THREAD

**Issue by appukonrad** [Fabrik/fabrik#1821]
**Testing server:** Joomla 3.7.0,PHP 7.1.3,MariaDB 10.1.22,Nginx 1.10.11,Fabrik git - master 

0 Could not connect to database. in admin backend - show data

Lists -> Show data 

**Return:**
0 Could not connect to database.
Call stack

**Function	Location**
1	JApplicationCms->execute()	/srv/http/mestolysa/public_html/administrator/index.php:51
2	JApplicationAdministrator->doExecute()	/srv/http/mestolysa/public_html/libraries/cms/application/cms.php:265
3	JApplicationAdministrator->dispatch()	/srv/http/mestolysa/public_html/libraries/cms/application/administrator.php:156
4	JComponentHelper::renderComponent()	/srv/http/mestolysa/public_html/libraries/cms/application/administrator.php:98
5	JComponentHelper::executeComponent()	/srv/http/mestolysa/public_html/libraries/cms/component/helper.php:369
6	require_once()	/srv/http/mestolysa/public_html/libraries/cms/component/helper.php:394
7	JControllerLegacy->execute()	/srv/http/mestolysa/public_html/administrator/components/com_fabrik/fabrik.php:86
8	FabrikAdminControllerList->view()	/srv/http/mestolysa/public_html/libraries/legacy/controller/legacy.php:710
9	JCacheControllerView->get()	/srv/http/mestolysa/public_html/administrator/components/com_fabrik/controllers/list.php:153
10	FabrikViewList->display()	/srv/http/mestolysa/public_html/libraries/joomla/cache/controller/view.php:98
11	FabrikViewListBase->display()	/srv/http/mestolysa/public_html/components/com_fabrik/views/list/view.html.php:41
12	FabrikFEModelList->getTmpl()	/srv/http/mestolysa/public_html/components/com_fabrik/views/list/view.base.php:392
13	FabrikFEModelList->getTable()	/srv/http/mestolysa/public_html/components/com_fabrik/models/list.php:11057
14	FabrikString::safeColName()	/srv/http/mestolysa/public_html/components/com_fabrik/models/list.php:3910
15	FabrikWorker::getDbo()	/srv/http/mestolysa/public_html/components/com_fabrik/helpers/string.php:115
16	FabrikWorker::bigSelects()	/srv/http/mestolysa/public_html/components/com_fabrik/helpers/parent.php:1679
17	JDatabaseDriverMysqli->getVersion()	/srv/http/mestolysa/public_html/components/com_fabrik/helpers/parent.php:1710
18	JDatabaseDriverMysqli->connect()	/srv/http/mestolysa/public_html/libraries/joomla/database/driver/mysqli.php:511
19	JDatabaseDriverMysqli->select()	/srv/http/mestolysa/public_html/libraries/joomla/database/driver/mysqli.php:192
20	()

**Comment by appukonrad** [comment]
Solve the problem re-enter the password in Fabrik -> Connections

**Comment by trob** [comment]
Please post such issues in the forums. GitHub is for confirmed code issues.
