### ISSUE TITLE
Fabrik visualization video playback issue

### ISSUE THREAD

**Issue by firojmahmud** [Fabrik/fabrik#1824]
I'm not sure is it a issue or a problem at my site.

I'm new to Fabrik, please spare me some help. In a website I use Fabrik visualization to show different images as a slideshow. One of the images has a Vimeo video in paused mode, once clicked on that video it will open in separate pop-up and then streaming the content. It has no issue on Chrome (PC) at all. But the real problem occurs when I try to play the video from android mobile devices. I use both Chrome & Firefox of mobile and found out that the video is not playing smoothly. I mean when I change the mobile position  from portrait to horizontal and vice-versa the video stops playing and the pop-up gone. I have to click again on that video box and once again pop-up shows with start playing from begining.

My environment details:
Joomla 3.6.4
Fabrik 3.5.1

Both Joomla & Fabrik has update available. Do I have to update both?
Is this a known issue? Please help. Appreciate any kinda help. Thanks in advance

Regards,
Firoj Mahmud

**Comment by cheesegrits** [comment]
Can you post questions like this in the forums, at http://fabrikar.com.  Github issues are for tracking confirmed bugs.
