### ISSUE TITLE
JS errors in import CSV view on J3.7.2

### ISSUE THREAD

**Issue by esedic** [Fabrik/fabrik#1833]
When I tried to import CSV I get JS errors and result are broken form elements (see screenshot).
I get this is console:
`Uncaught Error: Script error for: fab/fabrik
http://requirejs.org/docs/errors.html#scripterror
    at C (eval at <anonymous> (jquery.min.js:1), <anonymous>:8:252)
    at HTMLScriptElement.onScriptError (eval at <anonymous> (jquery.min.js:1), <anonymous>:29:514)
chosen-loader.js Failed to load resource: the server responded with a status of 404 (Not Found)
VM247:8 Uncaught Error: Script error for: fab/chosen-loader
http://requirejs.org/docs/errors.html#scripterror
    at C (eval at <anonymous> (jquery.min.js:1), <anonymous>:8:252)
    at HTMLScriptElement.onScriptError (eval at <anonymous> (jquery.min.js:1), <anonymous>:29:514)
tipsBootStrapMock.js Failed to load resource: the server responded with a status of 404 (Not Found)
index.php:8 Uncaught Error: Script error for: fab/tipsBootStrapMock
http://requirejs.org/docs/errors.html#scripterror
    at C (eval at <anonymous> (jquery.min.js:1), <anonymous>:8:252)
    at HTMLScriptElement.onScriptError (eval at <anonymous> (jquery.min.js:1), <anonymous>:29:514)`

![fabrik import csv fabrik administration](https://user-images.githubusercontent.com/617590/27148173-91c001d8-513f-11e7-9d87-713dfe06b162.png)

Using latest Fabrik from Github and Joomla 3.7.2 with PHP 5.6.24

**Comment by trob** [comment]
Confirmed.
It's ok with J!3.6.5, failing with J3.7.2

**Comment by cheesegrits** [comment]
I fixed the JS issues on front and backend with this commit:

https://github.com/Fabrik/fabrik/commit/f5a649636eac8a931ff12233316f17281762df9e

... but the weird widths on those elements is coming from a change to the Isis backend template in J! ...

https://github.com/joomla/joomla-cms/commit/2b6cb21b7d7830992920bcda6ee0eab12cf53a7f

... which adds max-width=100% to .controls ...

https://github.com/joomla/joomla-cms/blame/staging/administrator/templates/isis/css/template.css#L7388

And for reasons I don't understand, setting that max-width to 100% causes the effect you are seeing.

If anyone can figure out how to adapt our backend import view template ...

https://github.com/Fabrik/fabrik/blob/master/administrator/components/com_fabrik/views/import/tmpl/bootstrap.php

... to fix that, I'd be happy to apply any changes.

**Comment by cheesegrits** [comment]
Ah HAH!  It was a width-100 on a containing div.

Fixed.

https://github.com/Fabrik/fabrik/commit/38427a0ad9e9f273f860729ae6387366fa997b7d
