### ISSUE TITLE
List Icon not showing

### ISSUE THREAD

**Issue by deckyfx** [Fabrik/fabrik#1836]
Using Fabrik 3.6, Form, List, using layout default

In list view most icon for actions are not showing.

Also it should be nice if button in form also have icons

-------- Edit ------

I using Purity III and T3 framework, both using bootstrap, could it be style crash?

**Comment by trob** [comment]
Can you please post in the forums (or better search in the forums and WIKI before posting)?
http://fabrikar.com/forums/index.php?wiki/prerequisites/
https://github.com/Fabrik/Fabrik-Joomla-alt-layouts
