### ISSUE TITLE
Connexion update

### ISSUE THREAD

**Issue by Kilowogg** [Fabrik/fabrik#1848]
Hello,
I just did an update from 3.6 to 3.7 on my dev server which worked well.
After the update, I wanted to edit connexion informations in components, fabrik, connexions, but it ended with this error message.
In my case, this is not a big problem, I can just modify the connexion before updating fabrik. But this connexion edit should be working anyway.

Fatal error: Call to undefined method FabrikWorker::encryptCipher() in /administrator/components/com_fabrik/models/connection.php on line 175

Hope this'll help.

**Comment by trob** [comment]
Yup, see also http://fabrikar.com/forums/index.php?threads/error-when-editing-the-connection.47060/

**Comment by trob** [comment]
https://github.com/Fabrik/fabrik/commit/56c42d8dd7227fef392f843eadf50c1915f44000
