### ISSUE TITLE
Upload element with ajax delete class is wrong

### ISSUE THREAD

**Issue by deckyfx** [Fabrik/fabrik#1854]
the rendered html is

`<span data-isicon="true" class="fa   delete"></span>`

so its not render the fa icon, and cause no content in the span

for now i hack it by putting custom css .fa.delete with same value as .fa-minus-circle

also sugestion if uploaded file >= max upload, the "Add Files" button should be gone

**Comment by trob** [comment]
Can  you please post in the forums.
Issues are for confirmed Fabrik issues, not for questions about HTML/CSS or feature requests.

**Comment by deckyfx** [comment]
My bad, but i cannot do anything in forum since i can not register, i fail to find register button, and when o try to signup with facebook, it said its npt accepting new registrant
