### ISSUE TITLE
Default value "ALL" in FILTER

### ISSUE THREAD

**Issue by skater58** [Fabrik/fabrik#1856]
Hello! Could you help me how can I remove the default value "ALL" from FILTER? In what place of code I can fix it? Thank you in advance!
**I have now**
`<select id="ctl_judge_act___season_0value" name="fabrik___filter[list_6_com_fabrik_6][value][0]" class="inputbox fabrik_filter input-medium " size="1" data-filter-name="ctl_judge_act___season">
  <option value="" selected="selected">All</option>
  <option value="2">2017-2018</option>
  <option value="1">2016-2017</option>
  </select>`
**I want** 
`<select id="ctl_judge_act___season_0value" name="fabrik___filter[list_6_com_fabrik_6][value][0]" class="inputbox fabrik_filter input-medium " size="1" data-filter-name="ctl_judge_act___season">
  <option value="2" selected="selected">2017-2018</option>
  <option value="1">2016-2017</option>
  </select>`

**Comment by trob** [comment]
Can you please post in the forums.
Issues are for confirmed general issues, not for querstions.

**Comment by skater58** [comment]
Hello, my friend!

I can't join on favrikar.com((! There is an error every time, when I try to do this! I tried to use any e-mail of different domain, but it didn't help to solve this problem! Please!!!! Help me)) I want to join to you very much))

Thank you in advance!



Отправлено из мобильной Почты Mail.Ru


понедельник, 31 июля 2017 г., 15:00 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by trob** [comment]
Which email did you try, which error did you get?

**Comment by skater58** [comment]
I tried the folowing emails: skater58@mail.ru, saviour89@yandex.ru,  saviour070@gmail.com  and  fsrus_form@mail.ru )))
Error:
Notice
*  The following from address failed: hugh.messenger@gmail.com Warning
*  An error was encountered while sending the registration email. A message has been sent to the administrator of this site.


>Понедельник, 31 июля 2017, 15:51 +03:00 от troester <notifications@github.com>:
>
>Which email did you try, which error did you get?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Дмитрий ШАМОНИН

**Comment by trob** [comment]
Did you try to log in despite of the error (which is only a Notice)?
I just tested to register, could see the same notice but could login and post at the forums without problem.

**Comment by skater58** [comment]
In my case:

+  Error- 
*  Login error! You have not activated your account.
I didn't get any messages with confirmation ((


Отправлено из мобильной Почты Mail.Ru


понедельник, 31 июля 2017 г., 17:06 +0300 от notifications@github.com  <notifications@github.com>:

**Comment by skater58** [comment]
I could login at the forums too! But main part of site closed for login! Thanks!



Отправлено из мобильной Почты Mail.Ru


понедельник, 31 июля 2017 г., 17:06 +0300 от notifications@github.com  <notifications@github.com>:
