### ISSUE TITLE
System Generating PHP Warnings

### ISSUE THREAD

**Issue by drdehart** [Fabrik/fabrik#1863]
Using PHP 7.0.2:
We downloaded the entire component from the Github repo and updated the site - following the directions on the fabrikar.com site for updating from github. Updated the entire component, Manage/ClearCache, Discover, ... all looks good, but we still see these errors:
PHP Warning: array_combine(): Both parameters should have an equal number of elements in /home/sitename/public_html/plugins/fabrik_element/tags/tags.php on line 510
PHP Warning: array_unique() expects parameter 1 to be array, boolean given in /home/sitename/public_html/components/com_fabrik/helpers/html.php on line 2713
PHP Warning: Invalid argument supplied for foreach() in /home/sitename/public_html/components/com_fabrik/helpers/html.php on line 2715

**Comment by jaanusnurmoja** [comment]
html.php: 
array_unique() should be on line 2724
foreach() should be on line 2726
if you are using original master branch, not any customized code

**Comment by skuzmina** [comment]
We don't want to hack the component. Are you planing to release official fabrik version with the fix?

Please advise, 
Sandra

**Comment by simbus82** [comment]
With Joomla 3.8.0 i have new warnings:

`Warning: Declaration of FPagination::_item_inactive(JPaginationObject $item) should be compatible with Joomla\CMS\Pagination\Pagination::_item_inactive(Joomla\CMS\Pagination\PaginationObject $item) in /home/mysite/public_html/components/com_fabrik/helpers/pagination.php on line 0`

Is Fabrik ready for Joomla 3.8.0?

**Comment by trob** [comment]
> Is Fabrik ready for Joomla 3.8.0?

Which Fabrik are you running?
Can you please post in the forums if you have still warnings with the recent Fabrik version?
