### ISSUE TITLE
Error fileupload element when upload image >1Mb

### ISSUE THREAD

**Issue by nbiz2017** [Fabrik/fabrik#1864]
OP1: use upload element with Ajax upload on
 - Image <1Mb --> working ok
 - Image >1Mb --> upload image to folder server ok then click save, back to view list: column image --> empty.
OP2: use upload element with Ajax upload off
 - Image <1Mb --> working ok
  - Image >1Mb --> upload image to folder server ok then click save : 
> Notice: Undefined property: stdClass::$name_element_upload in \\path\to\server\plugins\fabrik_element\fileupload\fileupload.php on line 1649

![error upload 1](https://user-images.githubusercontent.com/30136016/30685288-9bdc2b00-9ede-11e7-9da4-d3515d4547d5.jpg)

**Comment by trob** [comment]
solved http://fabrikar.com/forums/index.php?threads/error-fileupload-element-when-upload-image-1mb.47472/#post-246751
