### ISSUE TITLE
Some visualization dont load/display database tables to choose

### ISSUE THREAD

**Issue by chidalgom1503** [Fabrik/fabrik#1866]
Hi all.

Recently I noticed some visualization plugins doesn't load any table to pick, it onlys display the connection dropdown, but nothing happens when the connection option are selected (no loading icon too). 

the plugins affected are:

Approvals
Calendar
Chart
Coverflow
Full calendar
Fusionchart
Googlemap
Timeline

The others plugins works fine, and display all the tables availables to choose from. I hope this can be fixed soon.

Joomla 3.8
Fabrik 3.7

Thanks!

**Comment by trob** [comment]
Can you please post in the forums?
As the forum announcement says Fabrik3.7 is not compatible with Joomla3.8.
You have to wait for the next release or update from GitHub.

**Comment by chidalgom1503** [comment]
Ok troester, many thanks!


2017-09-25 11:06 GMT-04:00 troester <notifications@github.com>:
