### ISSUE TITLE
Two fatal errors of Fabrik from PHP error log after J 3.8 upgrade

### ISSUE THREAD

**Issue by enricozamprogno** [Fabrik/fabrik#1869]
Both of them just updated from github

Sep 28 11:03:04 docdoom apache2: PHP Fatal error:  Cannot redeclare class FabrikHelperElement in /var/www/amministrazione-trasparente/components/com_fabrik/helpers/element.php on line 24

Sep 28 11:22:54 docdoom apache2: PHP Fatal error:  Class 'Fabrik\Helpers\JLog' not found in /var/www/joomla/libraries/fabrik/fabrik/Helpers/Worker.php on line 1703

The Fabrik\Helpers\JLog error occurs when you make a mistake in defining an element ( a syntax error in the expression of a calculated elements or a "concat" in a dropdown definition ), you get an eval exceptions AND you DONT'T have system debug active. If you have joomla system debug active the error display regularly and no fatal error occurs in PHP log.

**Comment by enricozamprogno** [comment]
The Fabrik\Helpers\JLog error occurs when you make a mistake in defining an element ( a syntax error in the expression of a calculated elements or a "concat" in a dropdown definition  ), you get an eval exceptions AND you DONT'T have system debug active. In the latter the error display regularly and no fatal error occurs in PHP log.

**Comment by trob** [comment]
Are you running a recent Fabrik GitHub update?

A syntax error in a calc element is throwing a Joomla system error message + a "Parse error: syntax error,..."
only if Fabrik Debug = Debug JS
nothing at all (just returning a blank calc field) if Fabrik Debug = No or Yes

but no Fatal error

**Comment by enricozamprogno** [comment]
I updated yesterday with github to fix the rss feed problem
Applying the patch the problem seems to be solved.

Thank you very much
