### ISSUE TITLE
problems with php form plugin after Joomla 3.8 upgrade 

### ISSUE THREAD

**Issue by oleksand** [Fabrik/fabrik#1871]
If you have several in a form (onload, onbeforeproces, onerror) resets everything keeping only the last one edited when you click save. also noticed it with the redirect plugin.. I had to go back to joomla 3.7.5

**Comment by trob** [comment]
Can you please post in the forums.
Common issue, several threads about it.
As Joomla says: "Before you update Joomla, ensure that the installed extensions are available for the new Joomla version."
Fabrik3.8 isn't out yet. You have to wait or update from GitHub.

**Comment by oleksand** [comment]
Ok thank you
