### ISSUE TITLE
Missing language text: COM_FABRIK_JOIN_NO_PK

### ISSUE THREAD

**Issue by Sophist-UK** [Fabrik/fabrik#1892]
Get COM_FABRIK_JOIN_NO_PK instead of error messages when I save element in a list which has no primary key defined.

**Comment by trob** [comment]
https://github.com/Fabrik/fabrik/commit/0eb1858a2a7f3795c4272c187159bb8eeb8374fc

**Comment by Sophist-UK** [comment]
Thanks.

**Comment by Sophist-UK** [comment]
Though error message was on a list which didn't have a join, so the error messages were very misleading.
