### ISSUE TITLE
Fullcalendar, remove element can't fire events of plugin

### ISSUE THREAD

**Issue by key4625** [Fabrik/fabrik#1938]
Hi, I've problem with the plugin full calendar and fabrik. 

I inserted in the events list plugin, some php code to synchronize with google calendar. When I use standard fabrik visualizzation the events are fired correctly (I use onDeleteRowsForm and onAfterDeleteRowsForm) , but when I use the full calendar visualization, the creation and modification take place correctly while the cancellation does not fire events. 

Someone have an idea?

**Comment by Sophist-UK** [comment]
Did you fix it yourself?

What was the problem?
