### ISSUE TITLE
Fix for the issue of "birthday" element throwing an error about about two identical IDs

### ISSUE THREAD

**Issue by xycofryx** [Fabrik/fabrik#2032]
Culprit: fabrik/plugins/fabrik_element/birthday/layouts/fabrik-element-birthday-form.php
On line: 12
Replace: day_id to year_id

**Comment by trob** [comment]
https://github.com/Fabrik/fabrik/commit/988c669f1562d77631c38e10b827e2b378660ad8
Thanks
