### ISSUE TITLE
Label positioning does not work at all (3.8.1)

### ISSUE THREAD

**Issue by hpheidinger** [Fabrik/fabrik#2036]
As the "Subject" says ...
Labels are _always_ put 'above' regardless what is switched in the
layout of the form or the layout of a group.
I am using Fabrik 3.8.1 with the the actual Joomla release 3.8.7 and have
cross-checked this on two machines. Same ill-behavior ...

**Comment by trob** [comment]
Please post in the forums and mention your Joomla template, your group settings etc.
This is for confirmed issues not for individual questions.
