### ISSUE TITLE
Fabrik datepicker problem for specific language

### ISSUE THREAD

**Issue by elenial89** [Fabrik/fabrik#2044]
Hello, I have used the datepicker in a form for my website and whereas it works perfect for all website languages, in English version it has a problem. When you click on datepicker it does not pop up the calendar but it is like trying to open it as only a line shows up under the picker like the photo below:
![image](https://user-images.githubusercontent.com/4612058/40650700-92433eee-633c-11e8-814e-d481682839fb.png)

Please help as datepicker is appropriate for us also in English version.

**Comment by Sophist-UK** [comment]
Please post in the Fabrikar forums if you need help or have a question. When you post there please post any JS errors you are getting.

**Comment by elenial89** [comment]
Ok thank you!
