### ISSUE TITLE
autocomplete dbjoin element get CORS error with Google Chrome and MS Edge

### ISSUE THREAD

**Issue by enricozamprogno** [Fabrik/fabrik#2066]
Google Chrome and MS Edge refuse Ajax connection for autocomplete dbjoin elements.
Works well with Mozilla Firefox.

Fabrik was just updated from gitHub

Error from Chrome console
> Failed to load https://rr.auslromagna.it/index.php?option=com_fabrik&format=raw&view=plugin&task=pluginAjax&g=element&element_id=2692&formid=144&plugin=databasejoin&method=autocomplete_options&package=fabrik: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://rr.auslromagna.it' is therefore not allowed access.

Error from Edge Console
>  SEC7120: [CORS] L'origine 'http://rr.auslromagna.it' non ha trovato 'http://rr.auslromagna.it' in response header Access-Control-Allow-Origin per la risorsa  cross-origin in 'https://rr.auslromagna.it/index.php?option=com_fabrik&format=raw&view=plugin&task=pluginAjax&g=element&element_id=2692&formid=144&plugin=databasejoin&method=autocomplete_options&package=fabrik'.

**Comment by Sophist-UK** [comment]
If you want support, please post in the fabrikar.com forums.

Github issues are reserved for logging confirmed bugs in Fabrik - and this is a webserver server configuration issue whereby you either need new or different HTTP headers included in your webpages and is very unlikely to be a Fabrik bug.

**Comment by enricozamprogno** [comment]
Ok.
I'll try something else.
Thank you

**Comment by Sophist-UK** [comment]
Even though this is not really a Fabrik issue I am sure you will get help if you use the Fabrikar forums.

If you are running an apache server, then you can use .htaccess to add the headers you need. If it is a different webserver, then you can probably do it by a different means.
