### ISSUE TITLE
Count in db->loadResult() invalid

### ISSUE THREAD

**Issue by BrunnoPrego** [Fabrik/fabrik#2067]
When enter in Fabrik Administrator Area it puts this this log message:
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /server-path/administrator/components/com_fabrik/fabrik.php on line 81, referer: http://serverurl/administrator/index.php?option=com_fabrik&view=crons

**Comment by BrunnoPrego** [comment]
Changing the line 81 from
if (count($db->loadResult()) === 0)
to
$result = $db->loadResult();
if (is_array($result) && count($result) === 0)

Should solve the warning

**Comment by Sophist-UK** [comment]
The current code says `if ((int)$db->loadResult() === 0)` which was changed over 5 months ago in commit 15ce396b4847f74e18057e18daf431f5dc2c2ffc as a 'Fix for PHP 7.2'.

So an update from Github should fix this for you.

**Comment by BrunnoPrego** [comment]
Ok, this is not in the released version 3.8.1. When this will be in a new released version?

**Comment by Sophist-UK** [comment]
Hugh makes fixes every week - but releases are infrequent,

If this was previously working on your site then you have obviously updated to the latest version of PHP without checking that your version of Joomla / Fabrik supports that version of PHP. Perhaps a quick question in the forums would have enabled you to find out before upgrading.

However I do believe that another release is imminent as soon as Hugh has the time (after updating the Fabrikar web sites).

**Comment by BrunnoPrego** [comment]
I dont "upgrade". it a new installation. I'm starting a new project and only installed a fresh joomla in a fresh httpd server with php 7.2 (more extended support time by now)

**Comment by Sophist-UK** [comment]
So you can either wait for a release - since you are still in development this doesn't seem like an issue.

Or you can update from Github.

**Comment by BrunnoPrego** [comment]
I think you misplaced what mean "issue", because, to the released version it is an issue, until a new release solving this. To me it was solved with my second comment code, and I opened this issue here thinking in help others from the community of component users, but, sorry if any help in that kind isn't appreciated by you.
When You tell it is solved here, I closed this issue, and only asked when this will be released, because in the released version, the problem will persist until it occurs.

Again, sorry about bother you with that.

**Comment by Sophist-UK** [comment]
No - in Github it is no longer an issue because it has been fixed.

Updating from Github is a standard thing to do with Fabrik if you want to fix a bug on your site which has already been fixed in Github. Fixes are too frequent and releases too infrequent for anyone  to be able to do otherwise.
