### ISSUE TITLE
Help with pdf generation

### ISSUE THREAD

**Issue by katzemary** [Fabrik/fabrik#2068]
I'm develope a system that has to generate a full report of the work to many academics realize throughout the year, consist in many forms that can have a lot of registers, and when the year end there must integrated all the forms in one pdf archive per academic and there must be consulted by differents types of users, I have a problem with the pdf generation, and with the javascript effects in the forms, i really really need help, i can´t found documentation, and i have the time on me. I used to asked in the forum but the access was denied, so i would like to pay for the complete technical advice, or something, i really need help

**Comment by Sophist-UK** [comment]
Github issues are for recording accepted bugs, not for asking how to questions.

Please close this issue and ask your question in the Fabrikar.com forums.

**Comment by katzemary** [comment]
I can't ask in the forum, the access is denied, and don't let me register
