### ISSUE TITLE
3.9 Classes - FormField.php  - Required for Joomla 3.9

### ISSUE THREAD

**Issue by felixkat** [Fabrik/fabrik#2072]
administrator/components/com_fabrik/classes/39/FormField.php   Required for Joomla 3.9

**Comment by foxcatbox** [comment]
I can confirm this. 

It's causing the following error message on the admin side: 

> "Fabrik cannot find files required for this version of Joomla. DO NOT use the Fabrik backend admin until this is resolved. Please visit our web site and check for announcements about this version" 

On the public side, it seems that search is not functioning any more.
