### ISSUE TITLE
unexpected * caused by 1024 * 1024

### ISSUE THREAD

**Issue by gadeynebram** [Fabrik/fabrik#2074]
This line

https://github.com/Fabrik/fabrik/blob/e0be6ae167fd131adf79bdc1b393cacc54e9b6ff/plugins/fabrik_element/fileupload/adaptors/filesystemstorage.php#L303

and this line

https://github.com/Fabrik/fabrik/blob/e0be6ae167fd131adf79bdc1b393cacc54e9b6ff/plugins/fabrik_element/fileupload/adaptor.php#L116

cause and error:

`Parse error: syntax error, unexpected '*', expecting ')' in /media/vwodannfs/www/joomla/plugins/fabrik_element/fileupload/adaptors/filesystemstorage.php on line 303`

We're currently using PHP 5.5.9.

**Comment by gadeynebram** [comment]
Yes, I know. We're using the Ubuntu 14.04 LTS stack which is only end of life in April and still provides 5.5. We've temporarily fixed this by replacing 1024 * 1024 by 1048576.

**Comment by trob** [comment]
see https://github.com/Fabrik/fabrik/commit/53300176ab2a9942b7c362e4b3dff7844abbe31c
