### ISSUE TITLE
Templates not showing in the layout tab

### ISSUE THREAD

**Issue by mbenba01** [Fabrik/fabrik#2192]
Hi guys,

I hope you are all well.
I have noticed the following issue with my fabrik. 
I am using the latest versions of both Fabrik and Joomla.

All template 'select' fields are not populated in the layout tab of the new list page.
I have tried a clean Joomla and Fabrik install in case this was caused by a plugin but the problem persists. 
You cannot choose a template when creating a new list as the field is empty. it's the same for front-end, admin and pdf templates.

**Comment by trob** [comment]
Please post your issues in the forum (ans search the forums before posting).
GitHub is for confirmed issues only.
This issue is because of a bug in Joomla3.9.16, it's solved in the recent Fabrik GitHub version

**Comment by mbenba01** [comment]
Thank you! and sorry for the inconvenience.
