### ISSUE TITLE
Fabrik + Sh404 - Fabrik upload element (ajax version) "page reloads" on delete

### ISSUE THREAD

**Issue by zibelian** [Fabrik/fabrik#2214]
**This happens with the file upload element (Ajax Version) only.**

Pressing on the X (delete) to delete the uploaded file, causes the page to reload, when sh404 is enabled.

I have talked to the sh404 developer, he told me that it might be (Fabrik) that causes the page reload, since sh404 SEF extension perfectly follows Joomla API.  Any ideas what can be the cause to this behaviour ?  

Cheers

**Comment by Sophist-UK** [comment]
The correct place for this is in the forums. I see that you have also posted it there, so please close it here.

**Comment by zibelian** [comment]
Yes, correct,  i am closing it here.
