### ISSUE TITLE
Problem after template update with Fabrik component

### ISSUE THREAD

**Issue by webmasterab** [Fabrik/fabrik#2217]
After the update of the template in Grantry joomla 3.9.22 to version 5.4.36 I got the following message.
Fatal error: Cannot declare class Joomla \ CMS \ Form \ FormField, because the name is already in use in administrator \ components \ com_fabrik \ classes \ 39 \ FormField.php on line 22

After investigation it appeared that the system plugin from Fabrik with version 3.9.2 or the component is causing the problems.

**Comment by cheesegrits** [comment]
I can't replicate this.  Which template?  I'm using Helium.

**Comment by webmasterab** [comment]
> I can't replicate this. Which template? I'm using Helium.

Hydrogen 

After updating the template to the latest version, Fabrik has problems with it and the entire backend is down with this message

**Comment by cheesegrits** [comment]
I have Hydrogen installed as well, so not sure why it's failing for you.

One thing you could try is making sure that the Fabrik system plugin loads first.  We have to override the standard JForms file in order to provide the "repeat" settings on the backend.  So if something else explicitly includes that J! file before our plugin gets to it, this can cause issues.

Using a database client of your choice (like phpMyAdmin), in the #__extensions table, find the row with 'name' plg_fabrik_system, and set the 'order' to -1.

**Comment by cheesegrits** [comment]
PS, do not edit and save anything Fabrik related on the backend until you get this resolved, as you will probably lose settings without our JForm override.

**Comment by webmasterab** [comment]
thank you. we will adjust and test it

**Comment by webmasterab** [comment]
If I update the pkg_gantry5 to the latest version and Fabrik latest version is installed then the backend chrasts and I have to restore a backup.

Are there more who suffer from this and how can we solve this.

The solutions mentioned above did not provide a solution

**Comment by trob** [comment]
Did you try to change the system plugin order?
Here https://fabrikar.com/forums/index.php?threads/fatal-error-on-admin.51977/
it is working

**Comment by webmasterab** [comment]
> Did you try to change the system plugin order?
> Here https://fabrikar.com/forums/index.php?threads/fatal-error-on-admin.51977/
> it is working

I have indeed tried that, but that did not go well in the test environment.

Will test a backup local one more time from the beginning

**Comment by webmasterab** [comment]
I just changed the ordering to -1 in phpmyadmin and was able to update now.
Thanks for this solution.
