### ISSUE TITLE
Template overrides not working after upgrade

### ISSUE THREAD

**Issue by mwanaJumuiya** [Fabrik/fabrik#2242]
I just upgraded to the new version of Fabrik 3.10 and suddenly the templates overrides which were working well are failing.

**Comment by lousyfool** [comment]
I think you'll want to discuss this in the forum. There, please provide more details, such as what exact layouts, where the override files are stored, etc.
https://fabrikar.com/forums/index.php?forums/community.99/

**Comment by mwanaJumuiya** [comment]
> I think you'll want to discuss this in the forum. There, please provide more details, such as what exact layouts, where the override files are stored, etc.
> https://fabrikar.com/forums/index.php?forums/community.99/

Thanks, I have opened one here https://fabrikar.com/forums/index.php?threads/after-upgrade-to-fabrik-3-10-the-template-overrides-are-not-working-anymore.52846/

**Comment by felixkat** [comment]
Forum post suggests this was resolved.
