### ISSUE TITLE
Export form list to CSV - modal freeze

### ISSUE THREAD

**Issue by emendo-web** [Fabrik/fabrik#2252]
Hi,

We have some difficulties when we try to export the form list to csv.

In console, we saw that de xhr url is truncate (no specials caracters).
We have identify that mootools 1.4.5 need the param : urlEncoded : false, in the Request.JSON.

But they seems to have other bugs.

Encounter error in : /media/com_fabrik/js/list.js :  around line 512

Is Fabrik compatible with Joomla 3.10.2 or 3.9.28 ?

Environnement :
JOOMLA : 3.10.2
PHP : 7.4.3
Fabrik : 3.10

Bests,
Seb.

**Comment by trob** [comment]
Can you please post in the forums.
