### ISSUE TITLE
Plugin FORM->Email - failure to load bootsttrap in the PDF attachment

### ISSUE THREAD

**Issue by iw5edv** [Fabrik/fabrik#2268]
in `plugins/fabrik_form/email/email.php`

to make bootstrap load in the creation of the PDF attachment 
add the following line after the n555

`FabrikhelperHTML::loadBootstrapCSS(true);`

**Comment by trob** [comment]
I can't replicate, CSS is loaded.

**Comment by iw5edv** [comment]
When I generate the PDF from the module page it loads CSS and bootstrap correctly. Mind when I send the email with the plugin the attached PDF loads css of the template but not bootstrap.
This way I can load it.

**Comment by trob** [comment]
https://github.com/Fabrik/fabrik/commit/b27f2e581a9b41900eaa365f6912a0f9abd0a189
