### ISSUE TITLE
UNABLE TO Register Need help urgently

### ISSUE THREAD

**Issue by runner26** [Fabrik/fabrik#2276]
I am not able to register account in Fabrik site validation email cannot be send so I can't activate my account. email used to register is hashbackend@gmail.com.....

I am creating a form using the latest Fabrik where it WILL need to validate the number entered does not exist in another table I have tried many PHP code to validate the value all in vain. Joomla! version 3.10.11

I have tried many coding like the following

> $db =& JFactory::getDBO();
> $query = "SELECT * FROM verifying_table WHERE number = 'number'";
> $db->setQuery($query);
> $db->query();
> $num_rows = $db->getNumRows();
> if($num_rows>0){
> // echo "Sold Out";
> }

**I get  Validation failed**

> 
> $myDb = JFactory::getDbo();
> $myQuery = $myDb->getQuery(true);
> $myQuery->select($myDb->quoteName('number'))
>     ->from($myDb->quoteName('verifying_table '));
> $myDb->setQuery($myQuery);
> $allvalues = $myDb->loadColumn();
> return in_array($data, $allvalues);

**I get  Validation failed**

I have tried using IF EXIST, SELECT COUNT (*) all comes with error

I really need help urgently

**Comment by trob** [comment]
To register in Fabrikar.com is not working at the moment.
http://fabrikar.com/forums/index.php?wiki/php-validation/

Your code must be in 'PHP code' (not Condition) and must return true or false.
Use e.g. 
var_dump($some-variable);
or
var_dump($some-variable);exit;
to see what you get.

BTW: there's a 'is unique value' validation (but I assume you'll need an account to download it).

**Comment by trob** [comment]
https://www.php.net/manual/en/function.var-dump.php
