### ISSUE TITLE
Table #__fabrik_log' doesn't exist

### ISSUE THREAD

**Issue by mratkajec0712** [Fabrik/fabrik#2278]
Hello,
I was following your installation steps. So, I've uploaded folders via ftp and installed through "discover" option. After enabling all plugins, my site crashed displaying message "Table '....#__fabrik_log' doesn't exist". Have I missed something?
Administration gives me the same error message too. Do you need any more details?

Kind regards

**Comment by trob** [comment]
If it's about Fabrik4 please use https://github.com/joomlahenk/fabrik/issues
If it's about Fabrik3 please use Fabrik forum.

In general: install via Joomla installer

**Comment by mratkajec0712** [comment]
Alright, I'm gonna post it on Fabrik forum, my apologies.

I tried to install plugin via Joomla installer, the popup throws me a message:

Warning
JInstaller: :Install: Can't find XML setup file.
Error
Path does not have a valid package.
Unable to detect manifest file.
