### ISSUE TITLE
what javascript for yesno element to check other element?

### ISSUE THREAD

**Issue by stefanocps** [Fabrik/fabrik#2283]
Hello i have a questionnaire with 35 questions and answer with a radiobutton.
I need to have a FLAG for all those records that have unanswered questions
The radiobutton will have a value = * to mean that no choice has been made, so unanswered
I have think to have a 'YESNO' element  to check if all the questions are answered.
If all are answered then the 'YESNO' will be 'YES'; if not then the 'YESNO' is 'NO'
SO basically it should check all radiobutton, if only one has * as value than the YESNO is NO

The YESNO should get its value on change of the radiobutton..but perhaps what i really need is on load/save..as i don't need it to see it in realtime. It should be just a reminder for me to see that some records are not totally answered

What javascript code should i use to get this done? anyhelp would be greatly apreciated

Thank you

**Comment by trob** [comment]
This is about F3 and about issues. Post questions is the forum.

**Comment by stefanocps** [comment]
sorry i don t understand

**Comment by trob** [comment]
In general GitHub "Issues" are for reporting issues/bugs in the code base, not for questions "How can I do...".
And anyway:
This is Fabrik 3  GitHub (for Joomla!3, which has reached its end-of-life 4 days ago).
