### ISSUE TITLE
Add 'pk' param to join when creating new join

### ISSUE THREAD

**Issue by cheesegrits** [Fabrik/fabrik#341]
Need to add the new 'pk' param to a join when creating new one, per this thread:

http://fabrikar.com/forums/showthread.php?p=145437#post145437

I added a TODO in makeNewJoin() in the backend list model, around line 962, with kinda sorta what I think we need to do, call the front end setJoinPK(), but I got confused between what $join needs to be in that context, if it's a model, or a table object.

Would also need to set setJoinPK() to public not protected if we do call it from there.

   -- hugh

**Comment by pollen8** [comment]
setJoinPK no longer exists  so guess this is not right now. closing . Re-open if you want to have a go at fixing it
