### ISSUE TITLE
FEATURE: clear filters button in filter form

### ISSUE THREAD

**Issue by cheesegrits** [Fabrik/fabrik#386]
Pretty please can we put the Clear Filter button in the top right of the list's filter form, where the old text "Clear" link used to be?

I know we moved it to the button bar because we added the option to have filters in the headers, hence we don't always have the filter form ... and we can keep it in the button bar to handle that situation, I just really really really would like it in it's old location as well.  And there'd be no harm in having it in two places.

   -- hugh

**Comment by pollen8** [comment]
this can be done with layouts now, closing
