### ISSUE TITLE
Add root path option back in to image element

### ISSUE THREAD

**Issue by cheesegrits** [Fabrik/fabrik#492]
See this thread:

http://fabrikar.com/forums/showthread.php?p=153997#post153997

... for whys and wherefores.

**Comment by pollen8** [comment]
ok you had 2.5 years , guess it wasn't that urgent. I'm closing this one. Feel free to reopen if you want to though

**Comment by cheesegrits** [comment]
Yeah, personally I'd rather junk the image element, and add "select existing file" as a feature of the upload element.

**Comment by jaanusnurmoja** [comment]
Hugh, will you open the issue "add "select existing file" as a feature of the upload element"? Would be nice!

**Comment by cheesegrits** [comment]
It's one of those things I'll probably just do one night when I get the
urge to just write some code and ignore support for a day. It's been on my
wish list for years, I hate the image element.

**Comment by jaanusnurmoja** [comment]
:+1:
