### ISSUE TITLE
Notice: Undefined property: FabrikFEModelForm

### ISSUE THREAD

**Issue by felixkat** [Fabrik/fabrik#493]
Notice: Undefined property: FabrikFEModelForm::$_data in  \components\com_fabrik\models\form.php on line 369

This happens whilsts loading a form via content plugin

**Comment by calichet** [comment]
hi, i'm using joomla 3.8.3 with Kabrik 3.8.0 

i'm trying to obtain the actual age with the fabrik element cal using the calculation:
ajax observe fields .. {datos_personales__fecha_nacimiento}
calculation return 
date_diff(date,datos_personales__fecha_nacimiento);

but the result says:

Notice: Undefined property: FabrikFEModelForm::$_data in D:\xampp\htdocs\cem\plugins\fabrik_element\calc\calc.php on line 477

Notice: Undefined property: FabrikFEModelForm::$_data in D:\xampp\htdocs\cem\plugins\fabrik_element\calc\calc.php on line 477

Notice: Undefined property: PlgFabrik_ElementCalc::$_id in D:\xampp\htdocs\cem\plugins\fabrik_element\calc\calc.php on line 547

please can you explain me how to solve thi issue..

thanks, regardas

Caliche

**Comment by trob** [comment]
Please post in the forums.
