### ISSUE TITLE
content plugin not showing element data

### ISSUE THREAD

**Issue by mglorencin** [Fabrik/fabrik#538]
Hi,

When using fabrik content plugin, specifically trying to show element data, it doesn't show element data, in fact it doesn't show me anything.

this works as is supposed to
{fabrik view=list id=13}

1.) but if I try
{fabrik view=element list=13 rowid=1 element=a_ideal_weight___comment}

but I have this data in my table, I can see it if I use the content plugin to show list data. Interesting to note, that I have this same form, same elements, set up on my old J1.5 site, with Fabrik2 and it works perfect. 

2.) In addition to this in Fabrik2 I used this code
{fabrik view=element table=13 rowid= element=a_ideal_weight___comment}
to show only last record in that table, but this also doesn't work anymore in Fabrik3. Don't know if you can use content plugin same way in Fabrik3 to show only last record in table. Useful when redirecting after calculation, to show the result inside some article.

I am using the very latest version via github on J2.5.8 / php.5.3.18 & latest versions of everything  as provided via yum update.

Kind regads,
Marck

**Comment by pollen8** [comment]
this seems to be fixed now. Calc on save = yes is giving me a couple of php warnings but it does display the data. I'll close this for now. Please feel free to reopen if this is still an issue.
