### ISSUE TITLE
Databasejoin add new option's behaviour not accurate in repeated group

### ISSUE THREAD

**Issue by jaanusnurmoja** [Fabrik/fabrik#583]
Mentioned also in https://github.com/Fabrik/fabrik/issues/569 that I closed as it was mainly solved. 

This issue occurs when 
a databasejoin element with add new option button is in repeated group 
AND 
we are editing an existing record

If we want to add new row to the repeated group and add there also a new option to the dbjoin
- then we have to click first on the 'add new' button near the dbjoin element on the first repeated row 
- and only after that we can click 'add group' and then on the same button near the same element on the new row.
Otherwise 
-  clicking save button doesn't close the popup
-  when we have also some element javascript action there (e.g. show element1 when element2 = 1) then it doesn't work at all

When we continue adding new rows during the same editing session then we don't need to open the 'first' popup anymore.

In case when we have succesfully populated the dbjoin element in new row with the newly added option 
- then all the previous dbjoin elements are automatically populated with the same new data (and we have to "restore" them). 
It doesn't happen 
- when we repeat this operation, 
- when we just choose an existing option for the new row 
- or when we edit the first row in this repeated group adding new option for the dbjoin element. 

P.S. a nonsense COULD NOT FIND RECORD IN DATABASE. is still present on the top of the popup.

**Comment by pollen8** [comment]
sounds like a corner case - I'm not even sure its still an issue.
Closing for now - please reopen if its still an issue.
