### ISSUE TITLE
New table procedure for repeat group

### ISSUE THREAD

**Issue by felixkat** [Fabrik/fabrik#92]
Consider the following setup.

Table_1 with a list of elements.  It is decided that Element_A needs to be in a repeat group.

A new group is created and placed into Table_1's form.  Element_A is then placed into group 'newgroup'.

In the physical back end a new table, (Table_1_Element_A_Repeat), is created and 'Element_A' is created in that new table.

With the current code 'Element_A' now resides in both tables,  Table_1    and   Table_1_Element_A_Repeat).  Entering data populates Table_1_Element_A_Repeat correctly but the frontend still displays data from Table_1.

Moving forward.  (as per discussions with Rob).

It is proposed that when the element is moved to the new group the physical data is moved as well and once complete the old field \ element is removed.

This may cause some concern with large tables so some saftey nets may have to be put in place.

**Comment by pollen8** [comment]
closing as we never got round to this  if its still an issue please re-open
